import { useEffect,useState,type FormEvent } from 'react';
import { z } from 'zod';
import { operationsStatusSchema,resetResultSchema,type OperationsStatus } from '@ground/contracts';
import { apiRequest } from '../../lib/api-client';
import { formatTimestamp } from '../../lib/formatters';
import { Button,Card,Field,ErrorState,LoadingState } from '../../ui';
import './operations.css';
const resultSchema=z.object({recorded:z.boolean().optional(),queued:z.boolean().optional(),message:z.string().optional()});
export function OperationsPanel({projectId,csrfToken}:{projectId:string;csrfToken:string}){const [status,setStatus]=useState<OperationsStatus|null>(null),[error,setError]=useState<string|null>(null),[pending,setPending]=useState(false),[message,setMessage]=useState<string|null>(null),[run,setRun]=useState('');async function load(){try{setStatus(await apiRequest(`/api/projects/${projectId}/operations/status`,{schema:operationsStatusSchema}));setError(null);}catch(cause){setError(cause instanceof Error?cause.message:'Operations status unavailable');}}useEffect(()=>{void load();},[projectId]);async function reset(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!status)return;setPending(true);try{const confirmation=String(new FormData(event.currentTarget).get('confirmation'));const result=await apiRequest(`/api/projects/${projectId}/runs/${status.run_id}/reset`,{method:'POST',schema:resetResultSchema,csrfToken,body:{expected_run_id:status.run_id,confirmation}});setMessage(result.message);if(result.status==='reset')window.location.assign(`/projects/${projectId}`);else await load();}catch(cause){setError(cause instanceof Error?cause.message:'Reset failed');}finally{setPending(false);}}
 return <Card title="Demo operations · administrator"><Button variant="secondary" onClick={()=>void load()}>Refresh status</Button>{error&&<ErrorState message={error}/>} {message&&<p role="status">{message}</p>}{!status?(error?null:<LoadingState label="Loading operation status"/>):<><p>{status.ready?'Ready for the configured rehearsal':'Setup or recovery needs attention'} · run {status.run_status}</p><p className="operations-id">Run: {status.run_id}</p><p>Worker: {status.worker_seen_at?formatTimestamp(status.worker_seen_at):'No heartbeat recorded'}</p><p>Pending inputs: {status.pending_inputs} · failed inputs: {status.failed_inputs}</p><p>Known provider spend: {status.budget.known_cost_usd===null?'Unknown':`US$${status.budget.known_cost_usd}`} · budget US$25 · warning US$20</p>{status.budget.has_unknown_costs&&<p>Some or all provider costs are unknown.</p>}{status.budget.warning&&<p role="alert">The known spend has reached the US$20 warning threshold.</p>}<ul>{status.providers.map(provider=><li key={provider.provider}>{provider.provider}: {provider.configured?'configured':'missing configuration'} · {provider.status}</li>)}</ul>{status.configuration_problems.length>0&&<details><summary>Configuration problems</summary><ul>{status.configuration_problems.map(problem=><li key={problem}>{problem}</li>)}</ul></details>}
 <h3>Pending and failed work</h3>{status.jobs.map(job=><div className="operations-job" key={job.id}><p>{job.kind} · {job.status} · attempts {job.attempts}</p>{job.last_error&&<p>{job.last_error}</p>}{job.reconcile_route&&<a href={job.reconcile_route}>Open request reconciliation</a>}{job.can_retry&&<form onSubmit={event=>{event.preventDefault();const reason=String(new FormData(event.currentTarget).get('reason'));void apiRequest(`/api/projects/${projectId}/jobs/${job.id}/retry`,{method:'POST',schema:resultSchema,csrfToken,body:{expected_status:'failed',reason}}).then(load).catch(cause=>setError(cause instanceof Error?cause.message:'Retry refused'));}}><Field name="reason" label="Reason for retry" required maxLength={1000}/><Button variant="secondary">Retry this known failure</Button></form>}</div>)}{status.jobs.length===0&&<p>No pending jobs.</p>}
 <h3>Unsettled writes</h3>{status.unsettled.length===0?<p>No unsettled writes recorded.</p>:status.unsettled.map(item=><div className="operations-job" key={`${item.kind}-${item.id}`}><p className="operations-id">{item.kind} · {item.id} · {item.status}</p>{item.kind==='request'?<a href={`/projects/${projectId}/requests`}>Reconcile quotation request</a>:['channel_reply','office_object','followup'].includes(item.kind)?<Observation projectId={projectId} csrfToken={csrfToken} runId={status.run_id} item={item} onSaved={load}/>:<p>Wait for the active provider lease to settle.</p>}</div>)}
 <h3>Run evidence</h3><label>Run to export<select value={run||status.run_id} onChange={event=>setRun(event.target.value)}>{status.runs.map(item=><option key={item.id} value={item.id}>{item.scenario_date} · {item.status} · {item.id.slice(0,8)}</option>)}</select></label><p><a href={`/api/projects/${projectId}/runs/${run||status.run_id}/export`}>Download redacted run evidence</a></p>
 <details><summary>Reset this demo run</summary><p>Old audit and run-labeled remote resources remain. Unsettled writes must be resolved first.</p><p className="operations-id">Type <code>RESET {status.run_id}</code></p><form onSubmit={event=>void reset(event)}><Field name="confirmation" label="Exact run confirmation" required autoComplete="off"/><Button variant="danger" loading={pending}>Reset to a fresh baseline</Button></form></details></>}</Card>;}
function Observation({projectId,csrfToken,runId,item,onSaved}:{projectId:string;csrfToken:string;runId:string;item:{kind:string;id:string;status:string};onSaved:()=>Promise<void>}){const [error,setError]=useState<string|null>(null);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await apiRequest(`/api/projects/${projectId}/runs/${runId}/observations`,{method:'POST',schema:resultSchema,csrfToken,body:{kind:item.kind,id:item.id,outcome:form.get('outcome'),provider_reference:form.get('reference')||null,note:form.get('note'),confirmation:form.get('confirmation')}});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'Observation refused');}}return <details><summary>Record an operator-reviewed outcome</summary><p>This records your observation, cancels the original job and permits reset. It does not retry or claim verified remote content.</p>{error&&<ErrorState message={error}/>}<form onSubmit={event=>void submit(event)}><label>Observed outcome<select name="outcome"><option value="confirmed_no_effect">Confirmed no external effect</option><option value="confirmed_delivered">Confirmed delivery</option><option value="located_remote">Located the old-run remote object</option></select></label><Field name="reference" label="Provider message or object reference"/><Field name="note" label="What you checked" minLength={10} maxLength={2000} required/><Field name="confirmation" label={`Type RESOLVE ${item.id}`} required/><Button variant="secondary">Record observation</Button></form></details>;}
