import { reportedProgress } from '@ground/domain';
import { GroundError,projectSnapshotSchema,type ActorContext,type ProjectRepository,type ProjectSnapshot,type TransactionContext } from '@ground/contracts';
import { PgTransactions } from '../../infra/database';
/** Context/catalog snapshot. Feature owners extend the canonical snapshot as their tables merge. */
export class PgProjectRepository implements ProjectRepository {
 constructor(private readonly transactions:PgTransactions) {}
 async snapshot(context:ActorContext,tx?:TransactionContext):Promise<ProjectSnapshot> { if(!tx)return this.transactions.run(current=>this.snapshot(context,current)); const db=this.transactions.client(tx);
 const active=await db.query("SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR SHARE",[context.run_id,context.project_id]);if(!active.rowCount)throw new GroundError('FORBIDDEN','Project context is no longer active');
 const project=await db.query<{version:number;event_sequence:string;scenario_version:string;scenario_date:string;name:string;timezone:string}>("SELECT p.name,COALESCE(p.configuration->>'timezone','America/Bogota') AS timezone,p.version,p.event_sequence,r.scenario_version,to_char(r.scenario_date,'YYYY-MM-DD') AS scenario_date FROM projects p JOIN scenario_runs r ON r.project_id=p.id JOIN members m ON m.project_id=p.id WHERE p.id=$1 AND r.id=$2 AND r.status='active' AND m.id=$3 FOR SHARE OF p",[context.project_id,context.run_id,context.actor_id]); const row=project.rows[0]; if(!row)throw new GroundError('FORBIDDEN','Project context is no longer active');
 const members=await db.query<{id:string;display_name:string;roles:string[]}>('SELECT id,display_name,roles FROM members WHERE project_id=$1 ORDER BY username',[context.project_id]);
 const locations=await db.query<{id:string;name:string;aliases:string[]}>('SELECT id,name,aliases FROM locations WHERE project_id=$1 ORDER BY name',[context.project_id]);
 const work=await db.query<{id:string;version:number;name:string;weight:string;status:string;location_id:string;area:string|null;allowance:string|null;material_id:string|null;required_date:string|null}>('SELECT id,version,name,weight,status,location_id,area,allowance,material_id,to_char(required_date,\'YYYY-MM-DD\') AS required_date FROM work_items WHERE project_id=$1 AND run_id=$2 ORDER BY name',[context.project_id,context.run_id]);
 const stock=await db.query<{id:string;code:string;name:string;unit:string;coverage:string|null;quantity:string;aliases:string[]}>('SELECT m.id,m.code,m.name,m.unit,m.coverage,m.aliases,COALESCE(sum(i.quantity),0)::text AS quantity FROM materials m LEFT JOIN inventory_movements i ON i.material_id=m.id AND i.project_id=m.project_id AND i.run_id=$2 WHERE m.project_id=$1 GROUP BY m.id ORDER BY m.code',[context.project_id,context.run_id]);
 const issues=await db.query<{id:string;version:number;location_id:string;description:string;observed_condition:string;status:string;evidence_ids:string[];drawing_reference:string;resolution_note:string|null}>('SELECT id,version,location_id,description,observed_condition,status,evidence_ids,drawing_reference,resolution_note FROM issues WHERE project_id=$1 AND run_id=$2 ORDER BY id',[context.project_id,context.run_id]);
 const tasks=await db.query<{id:string;version:number;issue_id:string;assignee_id:string;blocking_work_item_id:string;due_at:string;status:string;evidence_ids:string[]}>("SELECT id,version,issue_id,assignee_id,blocking_work_item_id,to_char(due_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') AS due_at,status,evidence_ids FROM assignments WHERE project_id=$1 AND run_id=$2 ORDER BY due_at",[context.project_id,context.run_id]);
 const needs=await db.query("SELECT id,material_id,activity_id,to_char(required_date,'YYYY-MM-DD') AS required_date,area,allowance,usable_stock,committed_stock,net_quantity,version,evidence_ids FROM procurement_needs WHERE project_id=$1 AND run_id=$2 ORDER BY required_date",[context.project_id,context.run_id]);
 return projectSnapshotSchema.parse({project_name:row.name,timezone:row.timezone,reported_progress:reportedProgress(work.rows),project_id:context.project_id,run_id:context.run_id,scenario_version:row.scenario_version,scenario_date:row.scenario_date,project_version:row.version,event_cursor:Number(row.event_sequence),members:members.rows.map(({id,...fields})=>({id,version:0,fields})),locations:locations.rows.map(({id,...fields})=>({id,version:0,fields})),work:work.rows.map(({id,version,...fields})=>({id,version,fields})),stock:stock.rows.map(({id,...fields})=>({id,version:row.version,fields})),issues:issues.rows.map(({id,version,...fields})=>({id,version,fields})),tasks:tasks.rows.map(({id,version,...fields})=>({id,version,fields})),needs:needs.rows,proposals:[],requests:[],decisions:[],remote_links:[]});
 }
}
