import { randomUUID } from 'node:crypto';
import { PgTransactions } from '../../infra/database';
import { hashPassword } from '../../infra/sessions';
import { manifestSchema,type DemoManifest,configurationProblems } from './manifest';
export const demoProjectId='00000000-0000-4000-8000-000000000001';
export async function configureDemo(transactions:PgTransactions,input:DemoManifest,passwords:Record<string,string|undefined>) {
 const manifest=manifestSchema.parse(input); const hashes=new Map<string,string>(); for(const member of manifest.members) { const password=passwords[member.username]; if(password)hashes.set(member.username,await hashPassword(password)); }
 await transactions.run(async tx=> { const db=transactions.client(tx); await db.query('INSERT INTO projects(id,name,configuration) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET configuration=excluded.configuration',[demoProjectId,manifest.project_name,manifest]);
 for(const member of manifest.members) { const existing=await db.query('SELECT 1 FROM members WHERE username=$1',[member.username]); const hash=hashes.get(member.username); if(!existing.rowCount&&!hash)throw new Error(`DEMO_PASSWORD_${member.username.toUpperCase()} is required for provisioning`); await db.query('INSERT INTO members(id,project_id,username,display_name,password_hash,roles,telegram_sender_id,remote_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(username) DO UPDATE SET display_name=excluded.display_name,roles=excluded.roles,telegram_sender_id=excluded.telegram_sender_id,remote_user_id=excluded.remote_user_id,password_hash=COALESCE($9,members.password_hash)',[randomUUID(),demoProjectId,member.username,member.name,hash??'',member.roles,member.telegram_sender_id,member.remote_user_id,hash??null]); }
 await db.query('DELETE FROM channel_bindings WHERE project_id=$1 AND chat_id IS DISTINCT FROM $2',[demoProjectId,manifest.telegram_chat_id]); if(manifest.telegram_chat_id)await db.query('INSERT INTO channel_bindings(chat_id,project_id) VALUES($1,$2) ON CONFLICT(chat_id) DO UPDATE SET project_id=excluded.project_id',[manifest.telegram_chat_id,demoProjectId]); }); return configurationProblems(manifest);
}
export async function seedDemo(transactions:PgTransactions,input:DemoManifest):Promise<string> { const manifest=manifestSchema.parse(input); return transactions.run(async tx=> { const db=transactions.client(tx); await db.query('SELECT id FROM projects WHERE id=$1 FOR UPDATE',[demoProjectId]); const existing=await db.query<{id:string}>("SELECT id FROM scenario_runs WHERE project_id=$1 AND status='active'",[demoProjectId]); if(existing.rows[0])return existing.rows[0].id;
 const runId=randomUUID(); await db.query("INSERT INTO scenario_runs(id,project_id,status,scenario_version,scenario_date) VALUES($1,$2,'active',$3,$4)",[runId,demoProjectId,manifest.scenario_version,manifest.scenario_date]);
 const bathroom='00000000-0000-4000-8000-000000000010',hallway='00000000-0000-4000-8000-000000000011',tile='00000000-0000-4000-8000-000000000020',cement='00000000-0000-4000-8000-000000000021';
 for(const [id,name,aliases] of [[bathroom,'Bathroom 2',['baño dos','baño 2']],[hallway,'Hallway',['pasillo']]])await db.query('INSERT INTO locations(id,project_id,name,aliases) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO NOTHING',[id,demoProjectId,name,aliases]);
 await db.query("INSERT INTO materials(id,project_id,code,name,unit,coverage,aliases) VALUES($1,$3,'POR-GRIS-60','Grey porcelain 60 × 60','box',1.26,ARRAY['porcelanato gris']),($2,$3,'CEM-50','Cement 50 kg','bag',NULL,ARRAY['cemento']) ON CONFLICT(id) DO NOTHING",[tile,cement,demoProjectId]);
 for(const [material,quantity,unit] of [[tile,'8','box'],[cement,'4','bag']])await db.query('INSERT INTO inventory_movements(id,project_id,run_id,material_id,quantity,unit,operation_key) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),demoProjectId,runId,material,quantity,unit,`baseline:${material}`]);
 for(const [name,weight,status] of [['Completed baseline','62','completed'],['Bathroom tiling','19','in_progress'],['Finishing','10','pending'],['Inspection','9','pending']])await db.query('INSERT INTO work_items(id,project_id,run_id,location_id,name,weight,status) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),demoProjectId,runId,bathroom,name,weight,status]);
 const wall=randomUUID(); await db.query("INSERT INTO work_items(id,project_id,run_id,location_id,name,weight,status,area,allowance,material_id,required_date) VALUES($1,$2,$3,$4,'Hallway tiling',0,'pending',22.5,0.10,$5,$6),($7,$2,$3,$8,'North-wall closure',0,'blocked',NULL,NULL,NULL,NULL)",[randomUUID(),demoProjectId,runId,hallway,tile,manifest.desired_delivery_date,wall,bathroom]); await db.query("INSERT INTO dependencies(id,project_id,run_id,work_item_id,description) VALUES($1,$2,$3,$4,'Wait for leak review')",[randomUUID(),demoProjectId,runId,wall]); return runId;
 }); }
