import Decimal from 'decimal.js';
import { GroundError,decimalSchema } from '@ground/contracts';
const Exact=Decimal.clone({precision:40,rounding:Decimal.ROUND_HALF_UP});
export function decimal(value:string) { decimalSchema.parse(value);return new Exact(value); }
export function add(left:string,right:string) {return decimal(left).plus(decimal(right)).toFixed();}
export function subtract(left:string,right:string) {return decimal(left).minus(decimal(right)).toFixed();}
export function multiply(left:string,right:string) {return decimal(left).times(decimal(right)).toFixed();}
export function moneyTotal(quantity:string,unitPrice:string) {return multiply(quantity,unitPrice);}
export function reportedProgress(work:readonly {weight:string;status:string}[]) { const total=work.reduce((sum,item)=>sum.plus(decimal(item.weight)),new Exact(0)); if(!total.eq(100))throw new GroundError('VALIDATION_ERROR','Work weights must total 100');return work.filter(item=>item.status==='completed').reduce((sum,item)=>sum.plus(decimal(item.weight)),new Exact(0)).toFixed(); }
export function materialNeed(input:{area:string;allowance:string;coverage:string;usable:string;committed:string}) {const area=decimal(input.area),allowance=decimal(input.allowance),coverage=decimal(input.coverage),usable=decimal(input.usable),committed=decimal(input.committed);if(area.isNegative()||allowance.isNegative()||!coverage.gt(0)||usable.isNegative()||committed.isNegative())throw new GroundError('VALIDATION_ERROR','Invalid material quantities');return Exact.max(0,area.times(allowance.plus(1)).div(coverage).ceil().minus(usable).minus(committed)).ceil().toFixed();}
export function convertQuantity(quantity:string,from:string,to:string,coverage:string|null,conversions:readonly {from_unit:string;to_unit:string;factor:string}[]=[]){if(from===to)return decimal(quantity).toFixed();if(from==='m2'&&to==='box'&&coverage&&decimal(coverage).gt(0)){const value=decimal(quantity).div(decimal(coverage));if(!value.isInteger())throw new GroundError('VALIDATION_ERROR','Area does not match whole boxes; confirm the unit');return value.toFixed();}if(from==='box'&&to==='m2'&&coverage)return multiply(quantity,coverage);const conversion=conversions.find(row=>row.from_unit===from&&row.to_unit===to);if(!conversion)throw new GroundError('VALIDATION_ERROR','Unknown material unit conversion');return multiply(quantity,conversion.factor);}
/** Offset compatible stock by area before rounding boxes of a candidate's coverage. */
export function candidateBoxes(input:{area:string;allowance:string;stock_boxes:string;committed_boxes:string;stock_coverage:string;candidate_coverage:string;stock_compatible:boolean}) {const area=decimal(input.area),allowance=decimal(input.allowance),coverage=decimal(input.candidate_coverage),stockCoverage=decimal(input.stock_coverage),stock=decimal(input.stock_boxes),committed=decimal(input.committed_boxes);if(area.isNegative()||allowance.isNegative()||!coverage.gt(0)||!stockCoverage.gt(0)||stock.isNegative()||committed.isNegative())throw new GroundError('VALIDATION_ERROR','Invalid candidate calculation inputs');const offset=input.stock_compatible?stock.plus(committed).times(stockCoverage):decimal('0');const boxes=Exact.max(0,area.times(allowance.plus(1)).minus(offset)).div(coverage).ceil();if(boxes.gt(Number.MAX_SAFE_INTEGER))throw new GroundError('VALIDATION_ERROR','Quantity exceeds supported range');return boxes.toNumber();}
