import { randomUUID } from 'node:crypto';
import { type Job } from '@ground/contracts';
import { materialNeed,decimal } from '@ground/domain';
import { stock } from './inventory';
import type { CommandScope,Mutation,SiteDependencies } from './types';
export function siteJob(scope:CommandScope,kind:Job['kind'],subject_id:string,version:number):Job {return {job_id:randomUUID(),kind,project_id:scope.context.project_id,run_id:scope.context.run_id,operation_id:scope.operation_id,dedupe_key:`${kind}:${scope.context.run_id}:${subject_id}:${version}`,payload_version:1,payload:{subject_id,expected_version:version},status:'pending',attempts:0,available_at:scope.context.trusted_time,due_at:null,lease_owner:null,lease_expires_at:null,last_error:null,condition:null,result_reference:null};}
export async function updateNeeds(scope:CommandScope,materialId:string,deps:SiteDependencies):Promise<Mutation>{const work=await scope.db.query<{id:string;area:string;allowance:string;required_date:string;coverage:string}>("SELECT w.id,w.area,w.allowance,to_char(w.required_date,'YYYY-MM-DD') AS required_date,m.coverage FROM work_items w JOIN materials m ON m.id=w.material_id WHERE w.project_id=$1 AND w.run_id=$2 AND w.material_id=$3 AND w.area IS NOT NULL AND m.coverage IS NOT NULL AND w.status<>'completed'",[scope.context.project_id,scope.context.run_id,materialId]);const mutation:Mutation={diff:[],events:[]};const usable=await stock(scope,materialId);
 for(const item of work.rows){const inbound=await scope.db.query<{quantity:string}>("SELECT COALESCE(sum(quantity),0)::text AS quantity FROM committed_deliveries WHERE project_id=$1 AND run_id=$2 AND material_id=$3 AND status='confirmed' AND due_date<=$4",[scope.context.project_id,scope.context.run_id,materialId,item.required_date]);const committed=inbound.rows[0]?.quantity??'0';const net=materialNeed({area:item.area,allowance:item.allowance,coverage:item.coverage,usable,committed});const existing=await scope.db.query<{id:string;version:number;net_quantity:string;usable_stock:string;committed_stock:string}>('SELECT id,version,net_quantity,usable_stock,committed_stock FROM procurement_needs WHERE run_id=$1 AND activity_id=$2 AND material_id=$3',[scope.context.run_id,item.id,materialId]);const previous=existing.rows[0];if(previous&&decimal(previous.net_quantity).eq(net)&&decimal(previous.usable_stock).eq(usable)&&decimal(previous.committed_stock).eq(committed))continue;const id=previous?.id??randomUUID(),version=(previous?.version??0)+1;
 await scope.db.query('INSERT INTO procurement_needs(id,project_id,run_id,material_id,activity_id,required_date,area,allowance,usable_stock,committed_stock,net_quantity,version,evidence_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(run_id,activity_id,material_id) DO UPDATE SET usable_stock=excluded.usable_stock,committed_stock=excluded.committed_stock,net_quantity=excluded.net_quantity,version=excluded.version,evidence_ids=excluded.evidence_ids',[id,scope.context.project_id,scope.context.run_id,materialId,item.id,item.required_date,item.area,item.allowance,usable,committed,net,version,scope.evidence_ids]);
 mutation.diff.push({entity_type:'need',entity_id:id,before:previous?{net_quantity:previous.net_quantity}:{},after:{net_quantity:net,usable_stock:usable,committed_stock:committed}});mutation.events.push({type:'need.changed',entity_id:id,version,summary:'Material need recalculated',fields:['net_quantity','usable_stock','committed_stock']});if(decimal(net).gt(0))await deps.queue.enqueue(siteJob(scope,'research_need',id,version),scope.tx);
 await scope.db.query('INSERT INTO proposal_change_intents(id,project_id,run_id,operation_id,need_id,need_version,reason) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),scope.context.project_id,scope.context.run_id,scope.operation_id,id,version,'Material availability changed']);await deps.invalidation?.changed({context:scope.context,operation_id:scope.operation_id,need_id:id,need_version:version,reason:'Material availability changed'},scope.tx);
 }
 return mutation;
}
