import { randomUUID } from 'node:crypto';
import { GroundError,actorContextSchema,operationProposalSchema,operationResultSchema,type ActorContext,type ExecutionEnvelope,type InventoryService,type OperationResult,type SiteCommandService,type TransactionContext } from '@ground/contracts';
import { decimal } from '@ground/domain';
import { consume,materialQuantity,movement } from './inventory';
import { completeWork,reportIssue,assignReview,updateAssignment,resolveIssue } from './work';
import { correct } from './corrections';
import { siteJob,updateNeeds } from './needs';
import type { CommandScope,Mutation,ReceiptMovement,SiteDependencies } from './types';
export class SiteService implements SiteCommandService,InventoryService {
 constructor(private readonly deps:SiteDependencies){}
 async execute(input:ExecutionEnvelope,tx?:TransactionContext):Promise<OperationResult>{if(!tx)return this.deps.transactions.run(current=>this.execute(input,current));const proposal=operationProposalSchema.parse(input.proposal);const scope=await this.scope(input.context,input.source_message_id,proposal.evidence_ids,tx);const duplicate=await this.prior(scope,input.idempotency_key,proposal);if(duplicate)return duplicate;if(proposal.expected_version!==scope.version)return this.result(scope,'conflict');
 let mutation:Mutation;
 switch(proposal.type){case 'complete_work_item':mutation=await completeWork(scope,proposal);break;case 'consume_material':mutation=await consume(scope,proposal);break;case 'report_issue':mutation=await reportIssue(scope,proposal);break;case 'assign_review':mutation=await assignReview(scope,proposal);break;case 'update_assignment':mutation=await updateAssignment(scope,proposal);break;case 'resolve_issue':mutation=await resolveIssue(scope,proposal);break;case 'correct_operation':mutation=await correct(scope,proposal);break;default:throw new GroundError('NOT_READY',`${proposal.type} is not registered yet`);}
 if(mutation.needs_input)return {...this.result(scope,'needs_input'),pending_actions:[{id:scope.operation_id,kind:'clarification',status:'needs_input',route:`/api/projects/${scope.context.project_id}/operations`}]};
 if(mutation.unchanged)return this.result(scope,'already_applied');
 for(const diff of [...mutation.diff])if(diff.entity_type==='inventory'){const needs=await updateNeeds(scope,diff.entity_id,this.deps);mutation.diff.push(...needs.diff);mutation.events.push(...needs.events);}
 for(const event of mutation.events)if(event.type==='assignment.updated')await this.deps.queue.enqueue(siteJob(scope,'sync_assignment',event.entity_id,event.version),tx);
 return this.commit(scope,mutation,input.idempotency_key,proposal);
 }
 async consume(input:ExecutionEnvelope,tx:TransactionContext){if(input.proposal.type!=='consume_material')throw new GroundError('VALIDATION_ERROR','Expected consumption');return this.execute(input,tx);}
 async receive(input:ReceiptMovement,tx?:TransactionContext):Promise<OperationResult>{if(!tx)return this.deps.transactions.run(current=>this.receive(input,current));const scope=await this.scope(input.context,input.receipt_line_id,input.evidence_ids,tx);if(!scope.context.roles.some(r=>['admin','supervisor','purchasing'].includes(r)))throw new GroundError('FORBIDDEN','Receipt permission required');const receiptProposal={type:'receipt_movement',material_id:input.material_id,quantity:input.quantity,unit:input.unit,receipt_line_id:input.receipt_line_id};const previous=await this.prior(scope,input.idempotency_key,receiptProposal);if(previous)return previous;if(input.expected_version!==scope.version)return this.result(scope,'conflict');if(!decimal(input.quantity).gt(0))throw new GroundError('VALIDATION_ERROR','Receipt quantity must be positive');const converted=await materialQuantity(scope,input.material_id,input.quantity,input.unit);const mutation=await movement(scope,input.material_id,converted.quantity,converted.unit);const needs=await updateNeeds(scope,input.material_id,this.deps);mutation.diff.push(...needs.diff);mutation.events.push(...needs.events);return this.commit(scope,mutation,input.idempotency_key,receiptProposal);}
 async history(context:ActorContext,evidenceId:string,tx?:TransactionContext):Promise<OperationResult[]>{if(!tx)return this.deps.transactions.run(current=>this.history(context,evidenceId,current));const scope=await this.scope(context,evidenceId,[],tx,true);const rows=await scope.db.query<{result:unknown}>('SELECT result FROM site_operations WHERE project_id=$1 AND run_id=$2 AND (source_message_id=$3 OR result->\'evidence_ids\' ? $3) ORDER BY created_at',[context.project_id,context.run_id,evidenceId]);return rows.rows.map(row=>operationResultSchema.parse(row.result));}
 private async scope(context:ActorContext,source:string,evidence:string[],tx:TransactionContext,readOnly=false):Promise<CommandScope>{const trusted=actorContextSchema.parse(context);const db=this.deps.transactions.client(tx);const run=await db.query(`SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR ${readOnly?'SHARE':'UPDATE'}`,[trusted.run_id,trusted.project_id]);if(!run.rowCount)throw new GroundError('CONFLICT','Scenario is no longer active');const project=await db.query<{version:number}>(`SELECT version FROM projects WHERE id=$1 FOR ${readOnly?'SHARE':'UPDATE'}`,[trusted.project_id]);const member=await db.query<{roles:unknown}>('SELECT roles FROM members WHERE id=$1 AND project_id=$2',[trusted.actor_id,trusted.project_id]);const row=member.rows[0];if(!row)throw new GroundError('FORBIDDEN','Project membership required');const roles=actorContextSchema.shape.roles.parse(row.roles);if(!roles.length)throw new GroundError('FORBIDDEN','Report permission required');for(const id of evidence){const valid=await db.query('SELECT id FROM ingestion_inputs WHERE id=$1 AND project_id=$2 AND run_id=$3 UNION ALL SELECT id FROM private_files WHERE id=$1 AND project_id=$2 AND run_id=$3',[id,trusted.project_id,trusted.run_id]);if(!valid.rowCount)throw new GroundError('FORBIDDEN','Evidence is outside this project');}return {db,context:{...trusted,roles},source_message_id:source,evidence_ids:evidence,operation_id:randomUUID(),version:project.rows[0]?.version??0,tx};}
 private async prior(scope:CommandScope,key:string,proposal:unknown){if(!key||key.length>200)throw new GroundError('VALIDATION_ERROR','Invalid idempotency key');const row=await scope.db.query<{result:unknown;actor_id:string;matches:boolean}>("SELECT result,actor_id,(proposal - 'expected_version')=($4::jsonb - 'expected_version') AS matches FROM site_operations WHERE project_id=$1 AND run_id=$2 AND idempotency_key=$3",[scope.context.project_id,scope.context.run_id,key,proposal]);const previous=row.rows[0];if(previous&&(previous.actor_id!==scope.context.actor_id||!previous.matches))throw new GroundError('CONFLICT','Idempotency key belongs to a different operation');return previous?{...operationResultSchema.parse(previous.result),status:'already_applied' as const}:null;}
 private result(scope:CommandScope,status:OperationResult['status']):OperationResult{return {operation_id:scope.operation_id,status,event_ids:[],state_diff:[],pending_actions:[],project_version:scope.version,evidence_ids:scope.evidence_ids};}
 private async commit(scope:CommandScope,mutation:Mutation,key:string,proposal:unknown):Promise<OperationResult>{const version=scope.version+1;await scope.db.query('UPDATE projects SET version=$1 WHERE id=$2',[version,scope.context.project_id]);const eventIds:string[]=[];
 for(const event of mutation.events){const sequence=await scope.db.query<{event_sequence:string}>('UPDATE projects SET event_sequence=event_sequence+1 WHERE id=$1 RETURNING event_sequence',[scope.context.project_id]);const eventId=randomUUID();await scope.db.query('INSERT INTO domain_events(event_id,project_id,run_id,sequence,project_version,operation_id,type,occurred_at,evidence_ids,payload,schema_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1)',[eventId,scope.context.project_id,scope.context.run_id,sequence.rows[0]?.event_sequence,version,scope.operation_id,event.type,scope.context.trusted_time,scope.evidence_ids,{entity_id:event.entity_id,entity_version:event.version,summary:event.summary,changed_fields:event.fields}]);eventIds.push(eventId);}
 const result=operationResultSchema.parse({...this.result(scope,'applied'),event_ids:eventIds,state_diff:mutation.diff,project_version:version});await scope.db.query('INSERT INTO site_operations(id,project_id,run_id,actor_id,source_message_id,idempotency_key,proposal,result) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[scope.operation_id,scope.context.project_id,scope.context.run_id,scope.context.actor_id,scope.source_message_id,key,proposal,result]);return result;}
}
