import {useEffect,useRef,useState,type FormEvent} from 'react';
import {requestListSchema,outboundRequestSchema,type RequestDetail} from '@ground/contracts';
import type {z} from 'zod';
import {apiRequest,emptyResponseSchema} from '../../lib/api-client';
import {formatTimestamp} from '../../lib/formatters';
import {Button,Card,EmptyState,ErrorState,Field,LoadingState,StatusBadge} from '../../ui';
import './requests.css';
type RequestList=z.infer<typeof requestListSchema>;
export function RequestsPanel({projectId,csrfToken}:{projectId:string;csrfToken:string}){
 const [data,setData]=useState<RequestList|null>(null),[error,setError]=useState<string|null>(null);
 async function refresh(){try{setData(await apiRequest(`/api/projects/${projectId}/requests`,{schema:requestListSchema}));setError(null);}catch(error){setError(error instanceof Error?error.message:'Could not load requests.');}}
 useEffect(()=>{const controller=new AbortController();let active=true;apiRequest(`/api/projects/${projectId}/requests`,{schema:requestListSchema,signal:controller.signal}).then(value=>{if(active)setData(value);},error=>{if(active)setError(error instanceof Error?error.message:'Could not load requests.');});return()=>{active=false;controller.abort();};},[projectId]);
 return <section className="requests-panel" aria-label="Quotation requests"><div className="requests-heading"><h2>Quotation requests</h2><Button variant="secondary" onClick={()=>void refresh()}>Refresh requests</Button></div>{error&&<ErrorState message={error}/>} {!data&&!error&&<LoadingState label="Loading sent requests…"/>}{data&&<RequestListView data={data} projectId={projectId} csrfToken={csrfToken} refresh={refresh}/>}</section>;
}
export function RequestListView({data,projectId,csrfToken,refresh}:{data:RequestList;projectId:string;csrfToken:string;refresh:()=>Promise<void>}){
 return <div className="request-list">{!data.requests.length&&<EmptyState title="No approved request queued">Requests appear here after an authorized supervisor approves the exact text and recipient.</EmptyState>}{data.requests.map(detail=><RequestCard key={detail.request.id} detail={detail} projectId={projectId} csrfToken={csrfToken} refresh={refresh}/>)}{data.unmatched_replies.map(reply=><Card key={reply.id} title="Reply needs request selection"><blockquote>{reply.text??'Media reply'}</blockquote><p className="g-metadata">Received {formatTimestamp(reply.received_at)} · Demo conversation {reply.chat_id}</p><LinkReply replyId={reply.id} requests={data.requests} projectId={projectId} csrfToken={csrfToken} refresh={refresh}/></Card>)}</div>;
}
function RequestCard({detail,projectId,csrfToken,refresh}:{detail:RequestDetail;projectId:string;csrfToken:string;refresh:()=>Promise<void>}){
 const request=detail.request;const status=request.status==='sending'?'pending':request.status==='cancelled'?'completed':request.status;
 return <article id={`request-${request.id}`}><Card title={`Request ${request.proposal_id.slice(0,8)}`}><p><StatusBadge status={status}/> <strong>{request.status==='pending'?'Approved · queued':request.status==='sending'?'Sending':request.status==='sent'?'Delivery confirmed':request.status==='uncertain'?'Delivery uncertain':request.status==='cancelled'?'Cancelled':'Send failed'}</strong></p><p>{detail.recipient_label} · Conversation {request.recipient_id}</p>{request.provider_message_id&&<p className="g-metadata">Telegram message {request.provider_message_id}</p>}{detail.sent_at&&<p className="g-metadata">Confirmed {formatTimestamp(detail.sent_at)}</p>}<details><summary>Exact approved text</summary><pre className="request-payload">{request.payload}</pre></details>{detail.last_error&&<ErrorState message={detail.last_error}/>} {detail.followup&&<div className="request-followup"><h3>Follow-up to Ana</h3><p>{detail.followup.status} · Due {formatTimestamp(detail.followup.due_at)}</p><p className="g-metadata">Sent only while this request still awaits a reply.</p>{detail.followup.last_error&&<p role="status">{detail.followup.last_error}</p>}</div>}{detail.replies.length>0&&<section aria-label="Recipient replies"><h3>Recipient replies</h3>{detail.replies.map(reply=><div className="request-reply" key={reply.id}><blockquote>{reply.text??'Media reply'}</blockquote><p className="g-metadata">{formatTimestamp(reply.received_at)} · Telegram message {reply.message_id}</p>{reply.evidence_ids.map(id=><a key={id} href={`/api/projects/${projectId}/files/${id}`} target="_blank" rel="noreferrer">View private reply attachment</a>)}</div>)}</section>}{detail.can_reconcile&&['sending','uncertain','failed'].includes(request.status)&&<ReconcileForm detail={detail} projectId={projectId} csrfToken={csrfToken} refresh={refresh}/>}</Card></article>;
}
function ReconcileForm({detail,projectId,csrfToken,refresh}:{detail:RequestDetail;projectId:string;csrfToken:string;refresh:()=>Promise<void>}){
 const [outcome,setOutcome]=useState('confirmed_sent'),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const key=useRef(crypto.randomUUID());
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError(null);try{await apiRequest(`/api/projects/${projectId}/requests/${detail.request.id}/reconcile`,{method:'POST',schema:outboundRequestSchema,csrfToken,idempotencyKey:key.current,body:{expected_status:detail.request.status,outcome,provider_message_id:outcome==='confirmed_sent'?String(form.get('message_id')):null,note:String(form.get('note')),evidence_ids:[]}});key.current=crypto.randomUUID();await refresh();}catch(error){setError(error instanceof Error?error.message:'Could not record the observation.');}finally{setBusy(false);}}
 return <form className="request-reconcile" onSubmit={event=>void submit(event)}><h3>Record a delivery observation</h3><p>Inspect the authorized demo conversation first. Recording this observation sends no message. A confirmed non-delivery needs a newly approved request before sending.</p><label>Observed outcome<select value={outcome} onChange={event=>setOutcome(event.target.value)}><option value="confirmed_sent">Message is present in the conversation</option><option value="confirmed_not_sent">Confirmed not delivered</option></select></label>{outcome==='confirmed_sent'&&<Field name="message_id" label="Observed Telegram message ID" required pattern="[0-9]+"/>}<Field name="note" label="What you checked" required maxLength={2000}/><label className="request-check"><input type="checkbox" required/> I checked the authorized conversation and recorded the observed result.</label>{error&&<ErrorState message={error}/>}<Button loading={busy} type="submit">Save observation</Button></form>;
}
function LinkReply({replyId,requests,projectId,csrfToken,refresh}:{replyId:string;requests:RequestDetail[];projectId:string;csrfToken:string;refresh:()=>Promise<void>}){
 const [selected,setSelected]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const eligible=requests.filter(item=>item.can_reconcile&&['sent','sending','uncertain'].includes(item.request.status));
 async function link(event:FormEvent){event.preventDefault();setBusy(true);try{await apiRequest(`/api/projects/${projectId}/requests/${selected}/replies/${replyId}/link`,{method:'POST',schema:emptyResponseSchema,csrfToken,body:{request_id:selected}});await refresh();}catch(error){setError(error instanceof Error?error.message:'Could not link the reply.');}finally{setBusy(false);}}
 if(!eligible.length)return <p>A supervisor must select the matching sent request.</p>;
 return <form className="request-link-form" onSubmit={event=>void link(event)}><label>Matching request<select required value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Select a request</option>{eligible.map(item=><option key={item.request.id} value={item.request.id}>{item.request.proposal_id.slice(0,8)} · {item.request.status}</option>)}</select></label>{error&&<ErrorState message={error}/>}<Button type="submit" loading={busy}>Link reply</Button></form>;
}
