ALTER TABLE outbound_requests ADD COLUMN sent_at timestamptz;
ALTER TABLE outbound_requests ADD COLUMN last_error text;
ALTER TABLE outbound_requests ADD COLUMN attempt_count integer NOT NULL DEFAULT 0;
ALTER TABLE outbound_requests ADD COLUMN retryable boolean NOT NULL DEFAULT false;
CREATE TABLE dispatch_replies(id uuid PRIMARY KEY,project_id uuid NOT NULL,run_id uuid NOT NULL,request_id uuid REFERENCES outbound_requests,bot_id text NOT NULL,update_id text NOT NULL,chat_id text NOT NULL,message_id text NOT NULL,sender_id text NOT NULL,reply_to_message_id text,text text,message jsonb NOT NULL,received_at timestamptz NOT NULL,UNIQUE(bot_id,update_id),UNIQUE(bot_id,chat_id,message_id),FOREIGN KEY(run_id,project_id) REFERENCES scenario_runs(id,project_id));
CREATE TABLE request_followups(id uuid PRIMARY KEY,project_id uuid NOT NULL,run_id uuid NOT NULL,request_id uuid NOT NULL UNIQUE REFERENCES outbound_requests,recipient_id text NOT NULL,due_at timestamptz NOT NULL,condition text NOT NULL,status text NOT NULL,provider_message_id text,attempted_at timestamptz,last_error text,FOREIGN KEY(run_id,project_id) REFERENCES scenario_runs(id,project_id));
CREATE TABLE dispatch_reconciliations(id uuid PRIMARY KEY,project_id uuid NOT NULL,run_id uuid NOT NULL,request_id uuid NOT NULL REFERENCES outbound_requests,actor_id uuid NOT NULL REFERENCES members,idempotency_key text NOT NULL,outcome text NOT NULL,provider_message_id text,note text NOT NULL,evidence_ids uuid[] NOT NULL,created_at timestamptz NOT NULL,UNIQUE(run_id,idempotency_key),FOREIGN KEY(run_id,project_id) REFERENCES scenario_runs(id,project_id));
CREATE TABLE operations_audit(id uuid PRIMARY KEY,project_id uuid NOT NULL,run_id uuid NOT NULL,actor_id uuid NOT NULL REFERENCES members,action text NOT NULL,subject_id uuid,reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(run_id,project_id) REFERENCES scenario_runs(id,project_id));
CREATE TABLE run_resets(old_run_id uuid PRIMARY KEY REFERENCES scenario_runs,new_run_id uuid NOT NULL REFERENCES scenario_runs,project_id uuid NOT NULL REFERENCES projects,actor_id uuid NOT NULL REFERENCES members,created_at timestamptz NOT NULL DEFAULT now());
