import { candidateCalculationSchema,type ProcurementNeed,type SupplierCandidate,type CandidateCalculation,type SourcingRow } from '@ground/contracts';
import { candidateBoxes,multiply,add,decimal } from '@ground/domain';
export function calculateCandidate(need:ProcurementNeed,candidate:SupplierCandidate,terms:{stock_coverage:string;transport:string|null;tax:string|null}):CandidateCalculation|null {
 if(!candidate.coverage||!decimal(candidate.coverage).gt(0))return null;
 const boxes=candidateBoxes({area:need.area,allowance:need.allowance,stock_boxes:need.usable_stock,committed_boxes:need.committed_stock,stock_coverage:terms.stock_coverage,candidate_coverage:candidate.coverage,stock_compatible:candidate.compatibility_status==='compatible'});
 const unresolved:string[]=[];let converted:string|null=null;
 if(candidate.published_price===null)unresolved.push('price');else if(candidate.currency!=='COP')unresolved.push('currency');else if(candidate.sale_unit==='box')converted=candidate.published_price;else if(candidate.sale_unit==='m2')converted=multiply(candidate.published_price,candidate.coverage);else unresolved.push('sale_unit');
 if(terms.transport===null)unresolved.push('transport');if(terms.tax===null)unresolved.push('tax');if(candidate.compatibility_status!=='compatible')unresolved.push('compatibility');if(!candidate.delivery_statement)unresolved.push('delivery');
 const subtotal=converted===null?null:multiply(String(boxes),converted);const total=subtotal!==null&&terms.transport!==null&&terms.tax!==null?add(add(subtotal,terms.transport),terms.tax):null;
 return candidateCalculationSchema.parse({candidate_id:candidate.id,candidate_version:1,need_id:need.id,need_version:need.version,required_boxes:boxes,unit_price_basis:candidate.sale_unit,converted_price:converted,material_subtotal:subtotal,known_transport:terms.transport,known_tax:terms.tax,known_total:total,unresolved_fields:unresolved,formula:'ceil(max(0, area × (1 + allowance) − compatible stock area) / candidate coverage)',inputs:{area:need.area,allowance:need.allowance,usable_stock:need.usable_stock,committed_stock:need.committed_stock,stock_coverage:terms.stock_coverage,candidate_coverage:candidate.coverage}});
}
export function rankCandidates(rows:readonly SourcingRow[]):SourcingRow[]{const compatibility={compatible:0,needs_review:1,unknown:2,incompatible:3},delivery={meets_date:0,unknown:1,late:2};return [...rows].sort((a,b)=>{const match=compatibility[a.candidate.compatibility_status]-compatibility[b.candidate.compatibility_status];if(match)return match;const date=delivery[a.delivery_status]-delivery[b.delivery_status];if(date)return date;const left=a.calculation?.material_subtotal,right=b.calculation?.material_subtotal;if(left===null||left===undefined)return right===null||right===undefined?0:1;if(right===null||right===undefined)return -1;return decimal(left).plus(a.known_transport??'0').plus(a.known_tax??'0').cmp(decimal(right).plus(b.known_transport??'0').plus(b.known_tax??'0'));});}
