import { randomUUID } from 'node:crypto';
import { dateSchema,supplierCandidateSchema,type SupplierCandidate } from '@ground/contracts';
import type { ExaPage } from '../../adapters/exa';
export interface RequiredMaterial {brand:string|null;reference:string|null;finish:string|null;name:string;coverage:string;}
function normalize(value:string){return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();}
function amount(value:string):string|null {const raw=value.replace(/\s/g,'');if(/^\d{1,3}(\.\d{3})+(,\d{1,2})?$/.test(raw))return raw.replaceAll('.','').replace(',','.');if(/^\d+(,\d{1,2})$/.test(raw))return raw.replace(',','.');return /^\d+(\.\d{1,2})?$/.test(raw)?raw:null;}
export function extractCandidate(page:ExaPage,queryId:string,sourceId:string,required:RequiredMaterial){const text=`${page.title??''}\n${page.text}`;const evidence:SupplierCandidate['evidence_by_field']={};
 const fact=(field:string,regex:RegExp)=>{const match=text.match(regex);if(!match?.[1])return null;evidence[field]={source_snapshot_id:sourceId,excerpt:match[0].slice(0,300)};return match[1].trim();};
 const reference=fact('reference',/(?:referencia|reference|ref\.)\s*[:\-]\s*([^\n;]{2,80})/i);const specification=fact('specification',/(?:acabado|finish|especificaci[oó]n)\s*[:\-]\s*([^\n;]{2,100})/i);const coverageRaw=fact('coverage',/(?:rendimiento|cobertura|coverage)\s*[:\-]?\s*(\d+(?:[.,]\d+)?)\s*m[²2]\s*(?:\/|por\s+)(?:caja|box)/i);const coverage=coverageRaw?.replace(',','.')??null;
 const priceMatch=text.match(/(?:precio|price)\s*[:\-]?\s*(?:COP\s*)?\$?\s*(\d[\d., ]*)\s*(COP)?\s*(?:\/|por\s+)?\s*(caja|box|m[²2])(?=\s|$|[.,;])/i);const price=priceMatch?.[1]?amount(priceMatch[1]):null;const saleUnit=priceMatch?.[3]?/^(caja|box)$/i.test(priceMatch[3])?'box':'m2':null;const currency=priceMatch&&/COP/i.test(priceMatch[0])?'COP':null;if(priceMatch){for(const field of ['published_price','sale_unit',...(currency?['currency']:[])])evidence[field]={source_snapshot_id:sourceId,excerpt:priceMatch[0].slice(0,300)};}
 const delivery=fact('delivery_statement',/(?:entrega|delivery)\s*[:\-]\s*([^\n;]{2,160})/i);const parsedDate=dateSchema.safeParse(delivery?.match(/\b(\d{4}-\d{2}-\d{2})\b/)?.[1]);const date=parsedDate.success?parsedDate.data:null;const transportText=fact('transport',/(?:transporte|transport|shipping|flete)\s*[:\-]\s*(?:COP\s*)?\$?\s*(\d[\d., ]*)\s*COP/i);const taxText=fact('tax',/(?:impuestos|tax|iva)\s*[:\-]\s*(?:COP\s*)?\$?\s*(\d[\d., ]*)\s*COP/i);
 let compatibility:SupplierCandidate['compatibility_status']='unknown';if(required.reference&&reference){if(normalize(required.reference)!==normalize(reference))compatibility='incompatible';else if(required.finish&&specification)compatibility=normalize(specification).includes(normalize(required.finish))?'compatible':'needs_review';else compatibility='needs_review';}
 evidence['merchant']={source_snapshot_id:sourceId,excerpt:page.url};
 if(page.title)evidence['product']={source_snapshot_id:sourceId,excerpt:page.title.slice(0,300)};
 return {candidate:supplierCandidateSchema.parse({id:randomUUID(),query_id:queryId,source_url:page.url,fetched_at:page.retrieved_at,merchant:new URL(page.url).hostname,product:page.title,reference,specification,compatibility_status:compatibility,sale_unit:saleUnit,coverage,published_price:price,currency,delivery_statement:delivery,evidence_by_field:evidence}),delivery_date:date,known_transport:transportText?amount(transportText):null,known_tax:taxText?amount(taxText):null};
}
export function publicQueries(required:RequiredMaterial):string[]{const terms=[required.brand,required.reference,required.finish].filter((term):term is string=>Boolean(term)).map(term=>term.replace(/[^\p{L}\p{N} ._-]/gu,' ').slice(0,60));return [`porcelanato 60x60 ${terms.join(' ')} Colombia`.replace(/\s+/g,' ').trim(),'porcelanato gris 60x60 Colombia'];}
