import { createHash,randomUUID } from 'node:crypto';
import { z } from 'zod';
import { GroundError,actorContextSchema,procurementNeedSchema,sourcingComparisonSchema,sourcingSelectionSchema,type ActorContext,type Job,type JobQueue,type ProcurementNeed,type ProjectRepository,type ResearchService,type SourcingComparison,type SourcingRow,type SourcingSelection,type TransactionContext } from '@ground/contracts';
import { PgTransactions } from '../../infra/database';
import { ExaClient,type ExaPage } from '../../adapters/exa';
import { extractCandidate,publicQueries,type RequiredMaterial } from './extraction';
import { calculateCandidate,rankCandidates } from './calculations';
const materialConfig=z.object({material:z.object({brand:z.string().nullable(),reference:z.string().nullable(),finish:z.string().nullable()})});
export class SourcingService implements ResearchService {
 constructor(private readonly deps:{transactions:PgTransactions;projects:ProjectRepository;queue:JobQueue;adapter:ExaClient}){}
 private async load(context:ActorContext,needId:string,tx:TransactionContext){const snapshot=await this.deps.projects.snapshot(context,tx);const need=snapshot.needs.find(item=>item.id===needId);if(!need)throw new GroundError('NOT_FOUND','Material need not found');const rows=await this.deps.transactions.client(tx).query<{configuration:unknown;name:string;coverage:string}>('SELECT p.configuration,m.name,m.coverage FROM projects p JOIN materials m ON m.project_id=p.id WHERE p.id=$1 AND m.id=$2',[context.project_id,need.material_id]);const row=rows.rows[0];if(!row)throw new GroundError('NOT_FOUND','Material not found');const config=materialConfig.parse(row.configuration);const required:RequiredMaterial={...config.material,name:row.name,coverage:row.coverage};return {need,required};}
 async enqueue(context:ActorContext,needId:string,version:number,key:string){return this.deps.transactions.run(async tx=>{const {need}=await this.load(context,needId,tx);if(need.version!==version)throw new GroundError('CONFLICT','Material need changed');const id=randomUUID();await this.deps.queue.enqueue({job_id:id,kind:'research_need',project_id:context.project_id,run_id:context.run_id,operation_id:randomUUID(),dedupe_key:`research_manual:${context.run_id}:${needId}:${version}:${key}`,payload_version:1,payload:{subject_id:needId,expected_version:version},status:'pending',attempts:0,available_at:context.trusted_time,due_at:null,lease_owner:null,lease_expires_at:null,last_error:null,condition:null,result_reference:null},tx);return {job_id:id};});}
 async process(job:Job){const row=await this.deps.transactions.pool.query<{id:string;roles:unknown}>('SELECT id,roles FROM members WHERE project_id=$1 ORDER BY username LIMIT 1',[job.project_id]);const member=row.rows[0];if(!member)throw new GroundError('NOT_READY','Project member is missing');const context=actorContextSchema.parse({actor_id:member.id,project_id:job.project_id,run_id:job.run_id,roles:member.roles,permissions:['research'],trusted_time:new Date().toISOString()});const need=await this.deps.transactions.run(async tx=>(await this.load(context,job.payload.subject_id,tx)).need);if(need.version!==job.payload.expected_version)return;await this.research(context,need);}
 async research(context:ActorContext,input:ProcurementNeed){const prepared=await this.deps.transactions.run(async tx=>{await this.deps.transactions.client(tx).query("SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR UPDATE",[context.run_id,context.project_id]);await this.deps.transactions.client(tx).query('SELECT id FROM projects WHERE id=$1 FOR UPDATE',[context.project_id]);const {need,required}=await this.load(context,input.id,tx);if(need.version!==input.version)throw new GroundError('CONFLICT','Material need changed');const db=this.deps.transactions.client(tx);const result=await db.query<{id:string;status:string;lease_expires_at:Date|null}>('SELECT id,status,lease_expires_at FROM sourcing_research WHERE run_id=$1 AND need_id=$2 AND need_version=$3 FOR UPDATE',[context.run_id,need.id,need.version]);const previous=result.rows[0];if(previous?.status==='completed'||(previous?.status==='researching'&&previous.lease_expires_at&&previous.lease_expires_at.getTime()>Date.now()))return {id:previous.id,need,required,done:true};const id=previous?.id??randomUUID();await db.query("INSERT INTO sourcing_research(id,project_id,run_id,need_id,need_version,status,lease_expires_at) VALUES($1,$2,$3,$4,$5,'researching',now()+interval '30 seconds') ON CONFLICT(run_id,need_id,need_version) DO UPDATE SET status='researching',error=NULL,lease_expires_at=now()+interval '30 seconds'",[id,context.project_id,context.run_id,need.id,need.version]);await this.event(context,need,'research.started',id,tx);return {id,need,required,done:false};});
 if(prepared.done)return (await this.rows(context,prepared.id)).map(row=>row.candidate);
 const signal=AbortSignal.timeout(20000);
 try {if(!this.deps.adapter.configured)throw new GroundError('NOT_READY','Exa key is not configured');const count=await this.deps.transactions.pool.query<{count:string}>('SELECT count(*)::text FROM sourcing_queries WHERE research_id=$1',[prepared.id]);const used=Number(count.rows[0]?.count??0);if(used>=2)throw new GroundError('PROVIDER_UNAVAILABLE','Research query budget exhausted; review the specification');const queries=publicQueries(prepared.required);let saved=0;
 for(let index=used;index<2;index++){const query=queries[index];if(!query)break;const queryId=randomUUID();await this.deps.transactions.pool.query('INSERT INTO sourcing_queries(id,research_id,project_id,run_id,query,duration_ms,created_at) VALUES($1,$2,$3,$4,$5,0,$6)',[queryId,prepared.id,context.project_id,context.run_id,query,new Date()]);const result=await this.deps.adapter.searchSupplierPages({query,limit:5,signal});let pages=result.pages;const missing=pages.filter(page=>!page.text);if(missing.length){const contents=await this.deps.adapter.getSupplierContents({urls:missing.map(page=>page.url),signal});pages=pages.map(page=>page.text?page:contents.find(content=>content.url===page.url)??page);}await this.deps.transactions.run(async tx=>{const current=await this.load(context,prepared.need.id,tx);if(current.need.version!==prepared.need.version)throw new GroundError('CONFLICT','Material need changed during research');await this.deps.transactions.client(tx).query('UPDATE sourcing_queries SET request_id=$1,duration_ms=$2 WHERE id=$3',[result.request_id,result.duration_ms,queryId]);for(const page of pages)await this.savePage(context,prepared.id,queryId,prepared.need,prepared.required,page,tx);});saved+=pages.length;if(saved>0)break;}
 await this.deps.transactions.run(async tx=>{await this.deps.transactions.client(tx).query("SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR UPDATE",[context.run_id,context.project_id]);await this.load(context,prepared.need.id,tx);await this.deps.transactions.client(tx).query("UPDATE sourcing_research SET status='completed',completed_at=now() WHERE id=$1",[prepared.id]);await this.event(context,prepared.need,'research.completed',prepared.id,tx);});
 }catch(error){await this.deps.transactions.run(async tx=>{await this.deps.transactions.client(tx).query("UPDATE sourcing_research SET status=$1,error=$2 WHERE id=$3",[error instanceof GroundError&&error.code==='NOT_READY'?'needs_configuration':'failed',error instanceof GroundError?error.message:'Research could not be completed',prepared.id]);await this.event(context,prepared.need,'research.failed',prepared.id,tx);});throw error;}
 return (await this.rows(context,prepared.id)).map(row=>row.candidate);
 }
 private async savePage(context:ActorContext,researchId:string,queryId:string,need:ProcurementNeed,required:RequiredMaterial,page:ExaPage,tx:TransactionContext){const id=randomUUID(),db=this.deps.transactions.client(tx);const extracted=extractCandidate(page,queryId,id,required);const calculation=calculateCandidate(need,extracted.candidate,{stock_coverage:required.coverage,transport:extracted.known_transport,tax:extracted.known_tax});await db.query('INSERT INTO source_snapshots(id,project_id,run_id,query_id,url,title,content,retrieved_at,provenance,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,context.project_id,context.run_id,queryId,page.url,page.title,page.text,page.retrieved_at,page.provenance,createHash('sha256').update(page.text).digest('hex')]);await db.query('INSERT INTO supplier_candidates(id,project_id,run_id,research_id,need_id,need_version,source_snapshot_id,candidate,calculation,delivery_date,delivery_status,known_transport,known_tax) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[extracted.candidate.id,context.project_id,context.run_id,researchId,need.id,need.version,id,extracted.candidate,calculation,extracted.delivery_date,extracted.delivery_date?extracted.delivery_date<=need.required_date?'meets_date':'late':'unknown',extracted.known_transport,extracted.known_tax]);}
 private async rows(context:ActorContext,researchId:string,tx?:TransactionContext):Promise<SourcingRow[]>{const db=tx?this.deps.transactions.client(tx):this.deps.transactions.pool;const rows=await db.query<{candidate:unknown;candidate_version:number;calculation:unknown;delivery_date:string|null;delivery_status:string;known_transport:string|null;known_tax:string|null;source:unknown}>("SELECT c.candidate,c.version AS candidate_version,c.calculation,to_char(c.delivery_date,'YYYY-MM-DD') AS delivery_date,c.delivery_status,c.known_transport,c.known_tax,jsonb_build_object('id',s.id,'url',s.url,'title',s.title,'retrieved_at',to_char(s.retrieved_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'),'excerpt',left(s.content,1200),'provenance',s.provenance) AS source FROM supplier_candidates c JOIN source_snapshots s ON s.id=c.source_snapshot_id WHERE c.research_id=$1 AND c.project_id=$2 AND c.run_id=$3",[researchId,context.project_id,context.run_id]);return z.array(sourcingComparisonSchema.shape.rows.element).parse(rows.rows);}
 async comparison(context:ActorContext,needId:string,tx?:TransactionContext):Promise<SourcingComparison>{if(!tx)return this.deps.transactions.run(current=>this.comparison(context,needId,current));const {need,required}=await this.load(context,needId,tx);if(!context.roles.some(role=>['admin','supervisor','purchasing'].includes(role)))throw new GroundError('FORBIDDEN','Supplier cost access required');const research=await this.deps.transactions.client(tx).query<{id:string;status:string;error:string|null}>('SELECT id,status,error FROM sourcing_research WHERE run_id=$1 AND need_id=$2 AND need_version=$3',[context.run_id,needId,need.version]);const record=research.rows[0];const rows=record?rankCandidates(await this.rows(context,record.id,tx)).slice(0,3):[];return sourcingComparisonSchema.parse({need,status:record?.status??'pending',error:record?.error??null,specification:[required.name,required.brand,required.reference,required.finish].filter(Boolean).join(' · '),rows,unresolved_fields:[...(!required.reference?['commercial reference']:[]),...(!required.finish?['finish']:[]),...(rows.some(row=>row.candidate.compatibility_status==='compatible')?[]:['compatible supplier'])],can_view_costs:true});}
 async selection(context:ActorContext,needId:string,needVersion:number,candidateId:string|null):Promise<SourcingSelection>{return this.deps.transactions.run(async tx=>{const comparison=await this.comparison(context,needId,tx);if(comparison.need.version!==needVersion)throw new GroundError('CONFLICT','Material need changed');const row=candidateId?comparison.rows.find(item=>item.candidate.id===candidateId):null;if(candidateId&&!row)throw new GroundError('NOT_FOUND','Candidate is not in this comparison');if(row?.candidate.compatibility_status==='incompatible')throw new GroundError('VALIDATION_ERROR','Incompatible material cannot be selected');const snapshot=sourcingSelectionSchema.parse({id:randomUUID(),project_id:context.project_id,run_id:context.run_id,need:comparison.need,candidate:row?.candidate??null,candidate_version:row?.candidate_version??null,calculation:row?.calculation??null,specification:comparison.specification,unresolved_fields:[...comparison.unresolved_fields,...(row?.calculation?.unresolved_fields??['price','coverage','transport','tax','delivery'])],created_at:context.trusted_time});await this.deps.transactions.client(tx).query('INSERT INTO sourcing_selections(id,project_id,run_id,need_id,need_version,candidate_id,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7)',[snapshot.id,context.project_id,context.run_id,needId,needVersion,candidateId,snapshot]);return snapshot;});}
 async sourcesForRun(context:ActorContext,tx:TransactionContext){await this.deps.projects.snapshot(context,tx);return (await this.deps.transactions.client(tx).query<{id:string;url:string;title:string|null}>('SELECT id,url,title FROM source_snapshots WHERE project_id=$1 AND run_id=$2 ORDER BY retrieved_at',[context.project_id,context.run_id])).rows;}
 private async event(context:ActorContext,need:ProcurementNeed,type:'research.started'|'research.completed'|'research.failed',id:string,tx:TransactionContext){const db=this.deps.transactions.client(tx);const project=await db.query<{version:number;event_sequence:string}>("UPDATE projects SET version=version+1,event_sequence=event_sequence+1 WHERE id=$1 AND EXISTS(SELECT 1 FROM scenario_runs WHERE id=$2 AND project_id=$1 AND status='active') RETURNING version,event_sequence",[context.project_id,context.run_id]);const row=project.rows[0];if(!row)throw new GroundError('NOT_FOUND','Project missing');await db.query('INSERT INTO domain_events(event_id,project_id,run_id,sequence,project_version,operation_id,type,occurred_at,evidence_ids,payload,schema_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1)',[randomUUID(),context.project_id,context.run_id,row.event_sequence,row.version,id,type,new Date(),need.evidence_ids,{entity_id:need.id,entity_version:need.version,summary:type==='research.completed'?'Supplier research completed':type==='research.failed'?'Supplier research requires attention':'Supplier research started',changed_fields:['supplier_candidates']}]);}
}
