import { describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { candidateCalculationSchema,procurementNeedSchema,supplierCandidateSchema,type SourcingRow } from '@ground/contracts';
import { calculateCandidate,rankCandidates } from './calculations';
import { add } from '@ground/domain';
const need=procurementNeedSchema.parse({id:randomUUID(),material_id:randomUUID(),activity_id:randomUUID(),required_date:'2026-09-13',area:'22.5',allowance:'0.10',usable_stock:'0',committed_stock:'0',net_quantity:'20',version:1,evidence_ids:[]});
function row(price:string,transport:string|null,status:'compatible'|'needs_review',date:string,coverage='1.26',unit='box'):SourcingRow{const candidate=supplierCandidateSchema.parse({id:randomUUID(),query_id:randomUUID(),source_url:'https://example.com/fixture',fetched_at:'2026-09-12T12:00:00Z',merchant:'Synthetic fixture',product:'Fixture tile',reference:'DEMO',specification:'Grey 60x60',compatibility_status:status,sale_unit:unit,coverage,published_price:price,currency:'COP',delivery_statement:date,evidence_by_field:{}});return {candidate,candidate_version:1,calculation:calculateCandidate(need,candidate,{stock_coverage:'1.26',transport,tax:null}),delivery_date:date,delivery_status:date<=need.required_date?'meets_date':'late',known_transport:transport,known_tax:null,source:{id:randomUUID(),url:candidate.source_url,title:'Synthetic fixture',retrieved_at:candidate.fetched_at,excerpt:'Synthetic comparison data',provenance:'fixture'}};}
describe('sourcing critical calculations',()=>{
 it('ranks A before late B and different-shade C without inventing tax',()=>{const a=row('55000','30000','compatible','2026-09-13'),b=row('53000','20000','compatible','2026-09-15'),c=row('52000','25000','needs_review','2026-09-13');expect(rankCandidates([c,b,a]).map(r=>r.candidate.id)).toEqual([a.candidate.id,b.candidate.id,c.candidate.id]);expect(a.calculation?.required_boxes).toBe(20);expect(add(a.calculation!.material_subtotal!,a.known_transport!)).toBe('1130000');expect(add(b.calculation!.material_subtotal!,b.known_transport!)).toBe('1080000');expect(add(c.calculation!.material_subtotal!,c.known_transport!)).toBe('1065000');expect(a.calculation?.known_total).toBeNull();expect(a.calculation?.unresolved_fields).toContain('tax');});
 it('converts per-area price and normalizes stock area before rounding alternate coverage',()=>{const perArea=row('40000',null,'compatible','2026-09-13','1.26','m2');expect(perArea.calculation?.converted_price).toBe('50400');expect(perArea.calculation?.known_total).toBeNull();expect(perArea.calculation?.unresolved_fields).toContain('transport');const alt=row('60000','0','compatible','2026-09-13','1.5');const result=calculateCandidate({...need,usable_stock:'1'},alt.candidate,{stock_coverage:'1.26',transport:'0',tax:'0'});expect(result?.required_boxes).toBe(16);expect(candidateCalculationSchema.parse(result).known_total).toBe('960000');});
});

it.skipIf(!process.env['TEST_DATABASE_URL'])('persists sourced facts once and preserves active or uncertain report writes',async()=>{
 const {isolatedDatabase}=await import('../../infra/test-database');const {PgTransactions}=await import('../../infra/database');const {PgJobQueue}=await import('../../infra/jobs');const fixture=await isolatedDatabase(process.env['TEST_DATABASE_URL']!);const transactions=new PgTransactions(fixture.pool),queue=new PgJobQueue(transactions);const project=randomUUID(),run=randomUUID(),id=randomUUID();
 try{await fixture.pool.query("INSERT INTO projects(id,name) VALUES($1,'Coalescing fixture')",[project]);await fixture.pool.query("INSERT INTO scenario_runs(id,project_id,status,scenario_version,scenario_date) VALUES($1,$2,'active','fixture','2026-09-12')",[run,project]);const job:import('@ground/contracts').Job={job_id:id,kind:'sync_report',project_id:project,run_id:run,operation_id:randomUUID(),dedupe_key:'fixture-report',payload_version:1,payload:{subject_id:randomUUID(),expected_version:1},status:'pending',attempts:0,available_at:new Date().toISOString(),due_at:null,lease_owner:null,lease_expires_at:null,last_error:null,condition:null,result_reference:null};await transactions.run(tx=>queue.enqueueLatest(job,tx));const leased=await queue.claim('fixture',['sync_report']);expect(leased?.payload.expected_version).toBe(1);await transactions.run(tx=>queue.enqueueLatest({...job,payload:{...job.payload,expected_version:2}},tx));expect((await fixture.pool.query<{payload:{expected_version:number}}>('SELECT payload FROM scheduled_jobs WHERE job_id=$1',[id])).rows[0]?.payload.expected_version).toBe(1);await queue.settle(leased!);const next=await queue.claim('fixture',['sync_report']);expect(next?.payload.expected_version).toBe(2);await transactions.run(tx=>queue.enqueueLatest({...job,payload:{...job.payload,expected_version:3}},tx));await queue.settle(next!,new Error('Unknown provider outcome'));expect(await queue.claim('fixture',['sync_report'])).toBeNull();const held=await fixture.pool.query<{status:string;desired_job:{payload:{expected_version:number}}}>('SELECT status,desired_job FROM scheduled_jobs WHERE job_id=$1',[id]);expect(held.rows[0]?.status).toBe('uncertain');expect(held.rows[0]?.desired_job.payload.expected_version).toBe(3);

 const actor=randomUUID(),material=randomUUID(),work=randomUUID(),needId=randomUUID();await fixture.pool.query('UPDATE projects SET configuration=$2 WHERE id=$1',[project,{material:{brand:'Fixture',reference:'DEMO',finish:'Grey'}}]);await fixture.pool.query("INSERT INTO members(id,project_id,username,display_name,password_hash,roles) VALUES($1,$2,'fixture','Fixture','unused',ARRAY['supervisor'])",[actor,project]);await fixture.pool.query("INSERT INTO materials(id,project_id,code,name,unit,coverage,aliases) VALUES($1,$2,'DEMO','Fixture tile','box',1.26,ARRAY[]::text[])",[material,project]);await fixture.pool.query("INSERT INTO work_items(id,project_id,run_id,name,weight,status,area,allowance,material_id,required_date) VALUES($1,$2,$3,'Fixture plan',100,'pending',22.5,0.1,$4,'2026-09-13')",[work,project,run,material]);await fixture.pool.query("INSERT INTO procurement_needs(id,project_id,run_id,material_id,activity_id,required_date,area,allowance,usable_stock,committed_stock,net_quantity,version,evidence_ids) VALUES($1,$2,$3,$4,$5,'2026-09-13',22.5,0.1,0,0,20,1,ARRAY[]::uuid[])",[needId,project,run,material,work]);
 const {ExaClient}=await import('../../adapters/exa');const {SourcingService}=await import('./service');const {PgProjectRepository}=await import('../project/repository');let calls=0;const adapter=new ExaClient('fixture',async()=>{calls++;return new Response(JSON.stringify({results:[{url:'https://example.com/fixture',title:'Fixture tile',text:'Reference: DEMO\nFinish: Grey\nCoverage: 1.26 m2/box\nPrice: COP 55000 / box\nDelivery: 2026-09-13\nTransport: 30000 COP\nTax: 0 COP'}]}),{status:200});});const projects=new PgProjectRepository(transactions),service=new SourcingService({transactions,projects,queue,adapter});const context:import('@ground/contracts').ActorContext={actor_id:actor,project_id:project,run_id:run,roles:['supervisor'],permissions:['research','costs'],trusted_time:new Date().toISOString()};const persistedNeed=(await projects.snapshot(context)).needs[0]!;await service.research(context,persistedNeed);await service.research(context,persistedNeed);expect(calls).toBe(1);const comparison=await service.comparison(context,needId);expect(comparison.rows[0]?.candidate.reference).toBe('DEMO');expect(comparison.rows[0]?.calculation?.required_boxes).toBe(20);expect(comparison.rows[0]?.calculation?.known_total).toBe('1130000');
 }finally{await fixture.close();}
});
