import { useEffect,useState,type FormEvent } from 'react';
import { useAgent } from '@copilotkit/react-core/v2';
import { liveStateSchema,procurementViewSchema,procurementOptionsSchema,sourcingComparisonSchema,type ProcurementView,type ProcurementNeed,type SourcingComparison } from '@ground/contracts';
import type { DecisionRendererProps } from '../../copilot/workspace-provider';
import { apiRequest } from '../../lib/api-client';
import { formatMoney,formatDate } from '../../lib/formatters';
import { Button,Card,Field,ErrorState,LoadingState,SourceLink } from '../../ui';
import './procurement.css';
function RequestForm({projectId,csrfToken,need,existing,onSaved}:{projectId:string;csrfToken:string;need:Pick<ProcurementNeed,'id'|'version'|'required_date'>;existing?:ProcurementView;onSaved:()=>void}) {
 const [options,setOptions]=useState<ReturnType<typeof procurementOptionsSchema.parse>|null>(null),[comparison,setComparison]=useState<SourcingComparison|null>(null),[error,setError]=useState<string|null>(null),[pending,setPending]=useState(false);const [candidate,setCandidate]=useState(existing?.proposal.candidate_version?existing.proposal.candidate_id:''),[quantity,setQuantity]=useState(existing?String(existing.proposal.calculation.required_boxes):''),[reviewed,setReviewed]=useState(existing?.alternative_reviewed??false);
 useEffect(()=>{const controller=new AbortController();Promise.all([apiRequest(`/api/projects/${projectId}/procurement/options`,{schema:procurementOptionsSchema,signal:controller.signal}),apiRequest(`/api/projects/${projectId}/needs/${need.id}`,{schema:sourcingComparisonSchema,signal:controller.signal})]).then(([config,result])=>{setOptions(config);setComparison(result);}).catch((cause:unknown)=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Request details unavailable');});return()=>controller.abort();},[projectId,need.id]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!options?.configured||pending)return;setPending(true);setError(null);const form=new FormData(event.currentTarget);const body={need_id:need.id,need_version:comparison?.need.version??need.version,candidate_id:candidate||null,...(quantity?{quantity:Number(quantity)}:{}),desired_date:String(form.get('date')),address:String(form.get('address')),recipient_id:options.recipient_id,alternative_reviewed:reviewed,...(existing?{expected_version:existing.proposal.version}:{})};try{await apiRequest(existing?`/api/projects/${projectId}/proposals/${existing.proposal.id}`:`/api/projects/${projectId}/proposals`,{schema:procurementViewSchema,method:existing?'PATCH':'POST',body,csrfToken});onSaved();}catch(cause){setError(cause instanceof Error?cause.message:'Could not prepare request');}finally{setPending(false);}}
 return <form className="procurement-form" onSubmit={event=>void submit(event)}>{error&&<ErrorState message={error}/>} {!options?(error?null:<LoadingState label="Loading authorized request details"/>):<><label>Material source<select value={candidate} onChange={event=>{setCandidate(event.target.value);setQuantity('');setReviewed(false);}}><option value="">Required specification only · price to confirm</option>{comparison?.rows.map(row=><option key={row.candidate.id} value={row.candidate.id} disabled={row.candidate.compatibility_status==='incompatible'}>{row.candidate.product??row.candidate.source_url} · {row.candidate.compatibility_status.replaceAll('_',' ')}</option>)}</select></label><Field label="Boxes" type="number" min={1} max={100000} value={quantity} onChange={event=>setQuantity(event.target.value)} help="Leave blank to use the server-calculated quantity for this material."/><Field label="Desired delivery date" name="date" type="date" defaultValue={existing?.proposal.desired_date??need.required_date} required/><Field label="Authorized test address" name="address" defaultValue={existing?.proposal.address??options.address??''} required help="Must match the administrator-configured test destination."/><p>Demo recipient: {options.recipient_id??'Not configured'}</p><label className="procurement-review"><input type="checkbox" checked={reviewed} onChange={event=>setReviewed(event.target.checked)}/> I reviewed the selected alternative's specification and shade.</label>{!options.configured&&<p>Request preparation needs administrator configuration.</p>}<Button loading={pending} disabled={!options.configured}>{existing?'Save new version':'Prepare request for review'}</Button></>}</form>;
}
export function ProcurementApprovalCard({args,respond,csrfToken,projectId}:DecisionRendererProps&{csrfToken:string;projectId:string}){const parsed=procurementViewSchema.safeParse(args['view']);const [changing,setChanging]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);if(!parsed.success)return <Card title="Request unavailable"><p>Reload the workspace to retrieve the current reviewed version.</p></Card>;const view=parsed.data,p=view.proposal;
 async function decide(decision:'approve'|'reject'){if(!respond||!view.checkpoint_token)return;setPending(true);setError(null);try{await respond({proposal_id:p.id,proposal_version:p.version,decision,checkpoint_token:view.checkpoint_token});setMessage(decision==='approve'?'Approval recorded. The quotation request is queued for dispatch.':'Request rejected. Nothing was sent.');}catch(cause){setError(cause instanceof Error?cause.message:'Decision could not be recorded');}finally{setPending(false);}}
 return <Card title={`Review quotation request · version ${p.version}`} provider="CopilotKit"><p>{p.selected_specification}</p><p>{p.calculation.required_boxes} boxes · requested {formatDate(p.desired_date)}</p><p>Material subtotal: {formatMoney(p.calculation.material_subtotal)} · total: {p.calculation.known_total===null?'To confirm':formatMoney(p.calculation.known_total)}</p><p>Demo recipient: <strong>{p.recipient_id}</strong></p><p>Test address: {p.address}</p>{view.source_url&&view.source_fetched_at&&<SourceLink url={view.source_url} retrievedAt={view.source_fetched_at}/>}<p>To confirm: {[...new Set(view.unresolved_fields)].join(', ')||'Availability and lot/shade'}</p><pre className="procurement-exact-text">{p.exact_text}</pre><p className="g-metadata">This is a quotation request, not a purchase order, payment or receipt.</p>{view.amendment_required&&<p>A started request requires a separately approved amendment.</p>}{message&&<p role="status">{message}</p>}{error&&<ErrorState message={error}/>}<div className="procurement-actions"><Button loading={pending} disabled={Boolean(message)||!respond||!view.checkpoint_token||p.status!=='pending'} onClick={()=>void decide('approve')}>Approve &amp; send request</Button><Button variant="secondary" disabled={pending} onClick={()=>setChanging(value=>!value)}>Change</Button><Button variant="danger" disabled={Boolean(message)||pending||!respond||!view.checkpoint_token||p.status!=='pending'} onClick={()=>void decide('reject')}>Reject</Button></div>{changing&&projectId&&csrfToken?<RequestForm projectId={projectId} csrfToken={csrfToken} need={{id:p.need_id,version:p.need_version,required_date:p.desired_date}} existing={view} onSaved={()=>window.location.reload()}/>:changing?<p>Open the request editor below to change this version.</p>:null}</Card>;
}
export function ProcurementPanel({projectId,csrfToken}:{projectId:string;csrfToken:string}){const {agent}=useAgent({agentId:'ground'});const state=liveStateSchema.safeParse(agent.state);const [open,setOpen]=useState<string|null>(null);if(!state.success)return null;return <section className="procurement-panel" aria-label="Request preparation">{state.data.snapshot.needs.filter(need=>need.net_quantity!=='0').map(need=><Card key={need.id} title="Prepare a quotation request"><Button variant="secondary" onClick={()=>setOpen(open===need.id?null:need.id)}>Choose material and review request</Button>{open===need.id&&<RequestForm projectId={projectId} csrfToken={csrfToken} need={need} onSaved={()=>window.location.reload()}/>}</Card>)}{state.data.snapshot.proposals.map(proposal=><ProposalEditor key={`${proposal.id}:${proposal.version}`} projectId={projectId} csrfToken={csrfToken} proposalId={proposal.id} version={proposal.version}/>)}</section>;}
function ProposalEditor({projectId,csrfToken,proposalId,version}:{projectId:string;csrfToken:string;proposalId:string;version:number}){const [view,setView]=useState<ProcurementView|null>(null),[open,setOpen]=useState(false),[error,setError]=useState<string|null>(null);useEffect(()=>{if(!open)return;apiRequest(`/api/projects/${projectId}/proposals/${proposalId}?version=${version}`,{schema:procurementViewSchema}).then(setView).catch((cause:unknown)=>setError(cause instanceof Error?cause.message:'Request unavailable'));},[projectId,proposalId,version,open]);return <Card title={`Request ${proposalId.slice(0,8)} · version ${version}`}><Button variant="secondary" onClick={()=>setOpen(value=>!value)}>Change request version</Button>{error&&<ErrorState message={error}/>} {open&&view&&<RequestForm projectId={projectId} csrfToken={csrfToken} need={{id:view.proposal.need_id,version:view.proposal.need_version,required_date:view.proposal.desired_date}} existing={view} onSaved={()=>window.location.reload()}/>}</Card>;}
