import { randomUUID } from 'node:crypto';
import { GroundError, jobSchema, type Job, type JobQueue, type TransactionContext } from '@ground/contracts';
import { PgTransactions, systemClock, type Clock } from './database';
const writes = ['send_channel_reply','dispatch_request','sync_attachment','sync_assignment','sync_report','follow_up'];
function decode(row: Record<string,unknown>): Job { const result={...row}; delete result['desired_job']; for(const key of ['available_at','due_at','lease_expires_at']) if(result[key] instanceof Date) result[key]=result[key].toISOString(); return jobSchema.parse(result); }
export class PgJobQueue implements JobQueue {
 constructor(readonly transactions:PgTransactions,private readonly clock:Clock=systemClock) {}
 async enqueue(input:Job,tx:TransactionContext) { const job=jobSchema.parse(input); const client=this.transactions.client(tx); const keys=Object.keys(job); await client.query(`INSERT INTO scheduled_jobs (${keys.join(',')}) VALUES (${keys.map((_,i)=>`$${i+1}`).join(',')}) ON CONFLICT(dedupe_key) DO NOTHING`,Object.values(job)); await client.query('INSERT INTO outbox_entries(id,project_id,run_id,job_id) SELECT $1,project_id,run_id,job_id FROM scheduled_jobs WHERE dedupe_key=$2 ON CONFLICT(job_id) DO NOTHING',[randomUUID(),job.dedupe_key]); }
 async enqueueLatest(input:Job,tx:TransactionContext) { const job=jobSchema.parse(input); const db=this.transactions.client(tx); await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[job.dedupe_key]); const found=await db.query<{job_id:string;status:string;payload:{expected_version:number};desired_job:unknown}>('SELECT job_id,status,payload,desired_job FROM scheduled_jobs WHERE dedupe_key=$1 FOR UPDATE',[job.dedupe_key]);const current=found.rows[0];if(!current){await this.enqueue(job,tx);return;}const desired=current.desired_job?jobSchema.parse(current.desired_job):null;if(job.payload.expected_version<=Math.max(current.payload.expected_version,desired?.payload.expected_version??-1))return;if(current.status==='leased'||current.status==='uncertain'){await db.query('UPDATE scheduled_jobs SET desired_job=$1 WHERE job_id=$2',[job,current.job_id]);return;}const keys=Object.keys(job).filter(key=>key!=='job_id'&&key!=='dedupe_key');const values=keys.map(key=>Reflect.get(job,key));await db.query(`UPDATE scheduled_jobs SET ${keys.map((key,index)=>`${key}=$${index+1}`).join(',')},desired_job=NULL WHERE job_id=$${keys.length+1}`,[...values,current.job_id]); }
 async retryKnown(jobId:string,expectedStatus:'failed',tx:TransactionContext){const db=this.transactions.client(tx);const result=await db.query<Record<string,unknown>>('SELECT * FROM scheduled_jobs WHERE job_id=$1 FOR UPDATE',[jobId]);const row=result.rows[0];if(!row)throw new GroundError('NOT_FOUND','Job not found');const job=decode(row);if(job.status!==expectedStatus)throw new GroundError('CONFLICT','Only a known failed job can be retried');const active=await db.query("SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR UPDATE",[job.run_id,job.project_id]);if(!active.rowCount)throw new GroundError('CONFLICT','Job run is no longer active');await db.query("UPDATE scheduled_jobs SET status='pending',attempts=0,available_at=$2,lease_owner=NULL,lease_expires_at=NULL,last_error=NULL WHERE job_id=$1",[jobId,this.clock.now()]);}
 async cancelRun(runId:string,tx:TransactionContext){await this.transactions.client(tx).query("UPDATE scheduled_jobs SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL,desired_job=NULL WHERE run_id=$1 AND status IN ('pending','leased')",[runId]);}
 async settleObserved(jobId:string,outcome:'succeeded'|'cancelled',tx:TransactionContext){const db=this.transactions.client(tx);const result=await db.query("UPDATE scheduled_jobs SET status=$2,lease_owner=NULL,lease_expires_at=NULL,desired_job=NULL,last_error='Outcome recorded by authorized operator; see operations audit' WHERE job_id=$1 AND (status IN ('uncertain','failed') OR (status='leased' AND lease_expires_at<=now()))",[jobId,outcome]);if(!result.rowCount)throw new GroundError('CONFLICT','Job is active or already settled');}
 async claim(owner:string,kinds:Job['kind'][]):Promise<Job|null> { return this.transactions.run(async tx=> { const db=this.transactions.client(tx); const now=this.clock.now();
  await db.query("UPDATE scheduled_jobs SET status=CASE WHEN kind=ANY($2::text[]) AND condition IS DISTINCT FROM 'intake_media' AND condition IS DISTINCT FROM 'reply_media' THEN 'uncertain' ELSE 'pending' END,lease_owner=NULL,lease_expires_at=NULL,last_error='Worker lease expired' WHERE status='leased' AND lease_expires_at<$1",[now,writes]);
  const run=await db.query<{id:string}>("SELECT id FROM scenario_runs WHERE status='active' ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1"); if(!run.rows[0]) return null;
  const row=await db.query<Record<string,unknown>>("UPDATE scheduled_jobs SET status='leased',attempts=attempts+1,lease_owner=$1,lease_expires_at=$2 WHERE job_id=(SELECT job_id FROM scheduled_jobs WHERE run_id=$3 AND status='pending' AND available_at<=$4 AND (due_at IS NULL OR due_at<=$4) AND kind=ANY($5::text[]) ORDER BY available_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *",[owner,new Date(now.getTime()+120000),run.rows[0].id,now,kinds]); return row.rows[0]?decode(row.rows[0]):null;
 }); }
 async settle(job:Job,error?:unknown) { const safeFailure=error instanceof GroundError && error.retryable && error.code!=='UNCERTAIN'; const uncertain=error && !safeFailure && writes.includes(job.kind) && job.condition!=='intake_media' && job.condition!=='reply_media'; const retry=error && !uncertain && job.attempts<=3; const providerDelay=error instanceof Error && 'retry_after_ms' in error && typeof error.retry_after_ms==='number' && Number.isFinite(error.retry_after_ms)?Math.min(3600000,Math.max(0,error.retry_after_ms)):0; const delay=Math.max(providerDelay,[2000,10000,30000][Math.max(0,job.attempts-1)]??30000); const settled=await this.transactions.pool.query<{desired_job:unknown}>("UPDATE scheduled_jobs SET status=$1,available_at=$2,lease_owner=NULL,lease_expires_at=NULL,last_error=$3 WHERE job_id=$4 AND status='leased' AND lease_owner=$5 RETURNING desired_job",[error?(uncertain?'uncertain':retry?'pending':'failed'):'succeeded',new Date(this.clock.now().getTime()+delay+Math.floor(Math.random()*500)),error?'Handler failed; inspect authorized operation status':null,job.job_id,job.lease_owner]); const desired=settled.rows[0]?.desired_job;if(!error&&desired){await this.transactions.run(async tx=>{const db=this.transactions.client(tx);await db.query("UPDATE scheduled_jobs SET desired_job=NULL WHERE job_id=$1 AND status='succeeded'",[job.job_id]);await this.enqueueLatest(jobSchema.parse(desired),tx);});} }
 async tick(owner:string,handlers:Partial<Record<Job['kind'],(job:Job)=>Promise<void>>>) { await this.transactions.pool.query('INSERT INTO worker_heartbeats(id,seen_at) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET seen_at=excluded.seen_at',[owner,this.clock.now()]); const kinds=jobSchema.shape.kind.options.filter(kind=>handlers[kind]); const job=await this.claim(owner,kinds); if(!job) return false; try { const handler=handlers[job.kind]; if(!handler) throw new Error('Handler unavailable'); await handler(job); await this.settle(job); } catch(error) { await this.settle(job,error); } return true; }
}
