import { createHash,randomBytes,scrypt as scryptCallback,timingSafeEqual } from 'node:crypto';
import type { FastifyRequest } from 'fastify';
import type pg from 'pg';
import { GroundError, actorContextSchema, sessionSchema, type ActorContext, type Session } from '@ground/contracts';
import { systemClock,type Clock } from './database';
const scrypt=(password:string,salt:string,length:number):Promise<Buffer>=>new Promise((resolve,reject)=>scryptCallback(password,salt,length,(error,key)=>error?reject(error):resolve(key)));
export async function hashPassword(password:string) { if(password.length<12) throw new GroundError('VALIDATION_ERROR','Passwords must have at least 12 characters'); const salt=randomBytes(16).toString('hex'); const hash=await scrypt(password,salt,64); return `${salt}:${Buffer.from(hash).toString('hex')}`; }
async function verify(password:string,stored:string) { const [salt,hex]=stored.split(':'); if(!salt || !hex) return false; const expected=Buffer.from(hex,'hex'); const actual=Buffer.from(await scrypt(password,salt,64)); return expected.length===actual.length && timingSafeEqual(actual,expected); }
const digest=(token:string)=>createHash('sha256').update(token).digest('hex');
export class Sessions {
 constructor(private readonly pool:pg.Pool,readonly origin:string,private readonly clock:Clock=systemClock) {}
 cookie(token:string,maxAge=28800) { return `ground_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${this.origin.startsWith('https:')?'; Secure':''}`; }
 token(request:FastifyRequest) { return request.headers.cookie?.split(';').map(v=>v.trim()).find(v=>v.startsWith('ground_session='))?.slice(15)??''; }
 checkOrigin(request:FastifyRequest) { if(request.headers.origin!==this.origin) throw new GroundError('FORBIDDEN','Origin rejected'); }
 async login(username:string,password:string,ip:string):Promise<{token:string;session:Session}> { const key=digest(ip); const limit=await this.pool.query<{attempts:number}>("INSERT INTO login_attempts(key,attempts,window_start) VALUES($1,1,$2) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN login_attempts.window_start<$2-interval '15 minutes' THEN 1 ELSE login_attempts.attempts+1 END,window_start=CASE WHEN login_attempts.window_start<$2-interval '15 minutes' THEN $2 ELSE login_attempts.window_start END RETURNING attempts",[key,this.clock.now()]); if((limit.rows[0]?.attempts??100)>10) throw new GroundError('FORBIDDEN','Too many login attempts; try later');
 const result=await this.pool.query<{id:string;password_hash:string}>('SELECT id,password_hash FROM members WHERE username=$1',[username]); const member=result.rows[0]; const valid=await verify(password,member?.password_hash??'00000000000000000000000000000000:'+ '00'.repeat(64)); if(!member || !valid) throw new GroundError('UNAUTHORIZED','Invalid username or password');
 const token=randomBytes(32).toString('hex'); await this.pool.query('INSERT INTO sessions(token_hash,member_id,csrf_token,expires_at) VALUES($1,$2,$3,$4)',[digest(token),member.id,randomBytes(32).toString('hex'),new Date(this.clock.now().getTime()+28800000)]); return {token,session:await this.get(token)};
 }
 async get(token:string):Promise<Session> { if(!/^[a-f0-9]{64}$/.test(token)) throw new GroundError('UNAUTHORIZED','Sign in required'); const result=await this.pool.query<{id:string;username:string;display_name:string;roles:string[];project_id:string;csrf_token:string}>('SELECT m.id,m.username,m.display_name,m.roles,m.project_id,s.csrf_token FROM sessions s JOIN members m ON m.id=s.member_id WHERE token_hash=$1 AND expires_at>$2',[digest(token),this.clock.now()]); const row=result.rows[0]; if(!row) throw new GroundError('UNAUTHORIZED','Session expired'); return sessionSchema.parse({user:{id:row.id,username:row.username,display_name:row.display_name,roles:row.roles},project_ids:[row.project_id],csrf_token:row.csrf_token}); }
 async context(request:FastifyRequest,projectId:string):Promise<ActorContext> { const session=await this.get(this.token(request)); if(!session.project_ids.includes(projectId)) throw new GroundError('FORBIDDEN','Project access denied'); const run=await this.pool.query<{id:string}>("SELECT id FROM scenario_runs WHERE project_id=$1 AND status='active'",[projectId]); if(!run.rows[0]) throw new GroundError('NOT_READY','No active scenario'); return actorContextSchema.parse({actor_id:session.user.id,project_id:projectId,run_id:run.rows[0].id,roles:session.user.roles,permissions:permissions(session.user.roles),trusted_time:this.clock.now().toISOString()}); }
 async mutation(request:FastifyRequest) { this.checkOrigin(request); const session=await this.get(this.token(request)); if(request.headers['x-csrf-token']!==session.csrf_token) throw new GroundError('FORBIDDEN','CSRF token rejected'); if(!request.headers['idempotency-key']) throw new GroundError('VALIDATION_ERROR','Idempotency-Key is required'); }
 async logout(token:string) { await this.pool.query('DELETE FROM sessions WHERE token_hash=$1',[digest(token)]); }
}
export function permissions(roles:readonly string[]) { const allowed=new Set(['report:create','research','workspace_sync']); if(roles.some(r=>['admin','supervisor','purchasing'].includes(r))) for(const p of ['costs','address','procurement','purchases']) allowed.add(p); if(roles.some(r=>['admin','supervisor'].includes(r))) allowed.add('approve'); if(roles.includes('admin')) allowed.add('admin'); return [...allowed]; }
