import { z } from 'zod';
import { GroundError,type ExaAdapter } from '@ground/contracts';
const pageSchema=z.object({url:z.string().url(),title:z.string().nullable().optional(),text:z.string().optional(),id:z.string().optional()});
const responseSchema=z.object({results:z.array(pageSchema),requestId:z.string().optional()});
export interface ExaPage {url:string;title:string|null;text:string;retrieved_at:string;provenance:'live'|'cache';}
export function publicSourceUrl(value:string):string {const url=new URL(value);const host=url.hostname.toLowerCase();if(!['https:','http:'].includes(url.protocol)||url.username||url.password||!host.includes('.')||host==='localhost'||host.endsWith('.local')||host.endsWith('.internal')||/^(\d+\.){3}\d+$/.test(host)||host.includes(':'))throw new GroundError('VALIDATION_ERROR','Only public source URLs are allowed');url.hash='';return url.toString();}
export class ExaClient implements ExaAdapter {
 constructor(private readonly key:string,private readonly fetcher:typeof fetch=fetch){}
 get configured(){return Boolean(this.key);}
 private async request(path:'search'|'contents',body:unknown,signal:AbortSignal){if(!this.key)throw new GroundError('NOT_READY','Exa key is not configured');let response:Response;try{response=await this.fetcher(`https://api.exa.ai/${path}`,{method:'POST',headers:{'x-api-key':this.key,'content-type':'application/json'},body:JSON.stringify(body),signal});}catch{throw new GroundError('PROVIDER_UNAVAILABLE','Exa retrieval timed out or failed',true);}if(!response.ok)throw new GroundError('PROVIDER_UNAVAILABLE',`Exa returned HTTP ${response.status}`,response.status===429||response.status>=500);const declared=Number(response.headers.get('content-length')??0);if(declared>2*1024*1024)throw new GroundError('PROVIDER_UNAVAILABLE','Exa response exceeded the limit');if(!response.body)throw new GroundError('PROVIDER_UNAVAILABLE','Exa returned no body');const chunks:Uint8Array[]=[];let size=0;for await(const chunk of response.body){size+=chunk.byteLength;if(size>2*1024*1024)throw new GroundError('PROVIDER_UNAVAILABLE','Exa response exceeded the limit');chunks.push(chunk);}const parsed=responseSchema.safeParse(JSON.parse(Buffer.concat(chunks).toString('utf8')));if(!parsed.success)throw new GroundError('PROVIDER_UNAVAILABLE','Exa returned an unsupported response');return parsed.data;}
 async searchSupplierPages(input:{query:string;limit:number;signal?:AbortSignal}){const query=input.query.trim();if(!query||query.length>300)throw new GroundError('VALIDATION_ERROR','Invalid public search terms');const start=Date.now();const result=await this.request('search',{query,numResults:Math.min(5,Math.max(1,input.limit)),contents:{text:{maxCharacters:15000}}},input.signal??AbortSignal.timeout(20000));return {pages:this.pages(result.results),request_id:result.requestId??null,duration_ms:Date.now()-start};}
 async getSupplierContents(input:{urls:string[];signal?:AbortSignal}){if(input.urls.length>5)throw new GroundError('VALIDATION_ERROR','At most five source pages');const result=await this.request('contents',{urls:input.urls.map(publicSourceUrl),text:{maxCharacters:15000}},input.signal??AbortSignal.timeout(20000));return this.pages(result.results);}
 private pages(rows:z.infer<typeof pageSchema>[]):ExaPage[]{return rows.slice(0,5).map(row=>({url:publicSourceUrl(row.url),title:row.title??null,text:(row.text??'').slice(0,15000),retrieved_at:new Date().toISOString(),provenance:'live'}));}
 async search(query:string){return (await this.searchSupplierPages({query,limit:5})).pages.map(page=>({id:page.url,url:page.url,title:page.title}));}
 async contents(urls:string[]){return (await this.getSupplierContents({urls})).map(page=>({url:page.url,text:page.text,fetched_at:page.retrieved_at}));}
}
