import { useEffect,useState } from 'react';
import { useAgent } from '@copilotkit/react-core/v2';
import { z } from 'zod';
import { liveStateSchema,sourcingComparisonSchema,type SourcingComparison } from '@ground/contracts';
import { apiRequest } from '../../lib/api-client';
import { formatMoney,formatDate } from '../../lib/formatters';
import { Button,Card,ErrorState,LoadingState,SourceLink } from '../../ui';
import './sourcing.css';
export function SupplierComparisonCard({comparison,onResearch,pending}:{comparison:SourcingComparison;onResearch:()=>void;pending:boolean}){return <Card title="Supplier comparison" provider="Exa" actions={<Button variant="secondary" loading={pending} onClick={onResearch}>Research material</Button>}>
 <p>{comparison.specification}</p><p>Requested by {formatDate(comparison.need.required_date)} · {comparison.status.replaceAll('_',' ')}</p>{comparison.error&&<ErrorState message={comparison.error}/>}
 {comparison.rows.length?<div className="sourcing-table-scroll"><table className="sourcing-table"><thead><tr><th scope="col">Source and material</th><th scope="col">Compatibility / delivery</th><th scope="col">Quantity and known amounts</th></tr></thead><tbody>{comparison.rows.map(row=><tr key={row.candidate.id}><td><strong>{row.candidate.product??'Product details to confirm'}</strong><p>{row.candidate.reference??'Reference to confirm'}</p><SourceLink url={row.source.url} retrievedAt={row.source.retrieved_at} excerpt={Object.values(row.candidate.evidence_by_field).slice(0,2).map(e=>e.excerpt).join(' · ')}/><small>{row.source.provenance==='fixture'?'Synthetic fixture':row.source.provenance==='cache'?'Cached source':'Retrieved source'}</small></td><td><p>{row.candidate.compatibility_status==='compatible'?'Exact match':row.candidate.compatibility_status==='incompatible'?'Incompatible':'Needs review'}</p><p>{row.delivery_status==='late'?'Required-date conflict':row.delivery_status==='meets_date'?'Published date meets request':'Delivery to confirm'}</p><p>{row.candidate.delivery_statement??'No published delivery statement'}</p></td><td><p>{row.calculation?`${row.calculation.required_boxes} boxes`:'Coverage to confirm'}</p><p>Published: {row.candidate.currency==='COP'?formatMoney(row.candidate.published_price):'Price / currency to confirm'} {row.candidate.sale_unit??''}</p><p>Material: {formatMoney(row.calculation?.material_subtotal??null)}</p><p>Transport: {formatMoney(row.known_transport)}</p><p>Tax: {formatMoney(row.known_tax)}</p><p>Total: {row.calculation?.known_total!==null&&row.calculation?.known_total!==undefined?formatMoney(row.calculation.known_total):'To confirm'}</p><details><summary>Calculation and unresolved terms</summary><p>{row.calculation?.formula??'An explicit source coverage is required.'}</p>{row.calculation&&<dl>{Object.entries(row.calculation.inputs).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl>}<p>{row.calculation?.unresolved_fields.join(', ')??'Price, coverage and commercial terms need confirmation.'}</p></details></td></tr>)}</tbody></table></div>:<p>No priced comparison is available. The required specification can be used for an RFQ with unresolved terms; no merchant has been contacted.</p>}
 {comparison.unresolved_fields.length>0&&<p>To confirm: {comparison.unresolved_fields.join(', ')}.</p>}
 </Card>;}
function NeedComparison({projectId,needId,version,csrfToken}:{projectId:string;needId:string;version:number;csrfToken:string}){const [data,setData]=useState<SourcingComparison|null>(null),[error,setError]=useState<string|null>(null),[pending,setPending]=useState(false),[refresh,setRefresh]=useState(0);useEffect(()=>{const controller=new AbortController();apiRequest(`/api/projects/${projectId}/needs/${needId}`,{schema:sourcingComparisonSchema,signal:controller.signal}).then(setData).catch((cause:unknown)=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Research unavailable');});return()=>controller.abort();},[projectId,needId,version,refresh]);async function research(){setPending(true);setError(null);try{await apiRequest(`/api/projects/${projectId}/needs/${needId}/research`,{method:'POST',body:{expected_version:data?.need.version??version},schema:z.object({job_id:z.string().uuid()}),csrfToken});setRefresh(value=>value+1);}catch(cause){setError(cause instanceof Error?cause.message:'Research failed');}finally{setPending(false);}}return <>{error&&<ErrorState message={error}/>} {data?<SupplierComparisonCard comparison={data} onResearch={()=>void research()} pending={pending}/>:<LoadingState label="Loading supplier research"/>}</>;}
export function SourcingPanel({projectId,csrfToken}:{projectId:string;csrfToken:string}){const {agent}=useAgent({agentId:'ground'});const parsed=liveStateSchema.safeParse(agent.state);if(!parsed.success)return null;return <section className="sourcing-panel" aria-label="Material sourcing">{parsed.data.snapshot.needs.filter(need=>need.net_quantity!=='0').map(need=><NeedComparison key={need.id} projectId={projectId} needId={need.id} version={parsed.data.snapshot.project_version} csrfToken={csrfToken}/>)}</section>;}
