import { randomUUID,createHash } from 'node:crypto';
import type { PoolClient } from 'pg';
import { GroundError,actorContextSchema,operationProposalSchema,operationResultSchema,purchaseSchema,purchaseListSchema,type ActorContext,type ExecutionEnvelope,type InventoryReceiptService,type OperationProposal,type OperationResult,type Purchase,type PurchaseList,type TransactionContext } from '@ground/contracts';
import { add,decimal,moneyTotal } from '@ground/domain';
import type { PgTransactions } from '../../infra/database';
interface Scope {db:PoolClient;context:ActorContext;version:number;tx:TransactionContext;}
const key=(value:string|null)=>value?.normalize('NFKC').trim().toLocaleLowerCase('en').replace(/\s+/g,' ')||null;
const costs=(context:ActorContext)=>context.roles.some(role=>['admin','supervisor','purchasing'].includes(role));
const receive=(context:ActorContext)=>context.roles.some(role=>['admin','supervisor'].includes(role));
export class PurchaseService {
 constructor(private readonly deps:{transactions:PgTransactions;inventory:InventoryReceiptService}){}
 async execute(input:ExecutionEnvelope,tx?:TransactionContext):Promise<OperationResult>{
  if(!tx)return this.deps.transactions.run(current=>this.execute(input,current));
  const proposal=operationProposalSchema.parse(input.proposal);if(proposal.type!=='register_purchase'&&proposal.type!=='confirm_receipt')throw new GroundError('VALIDATION_ERROR','Expected purchase or receipt command');
  const scope=await this.scope(input.context,tx);if(proposal.type==='confirm_receipt'&&!receive(scope.context))throw new GroundError('FORBIDDEN','Supervisor receipt permission required');
  await this.evidence(scope,proposal.evidence_ids);
  if(!input.idempotency_key||input.idempotency_key.length>200)throw new GroundError('VALIDATION_ERROR','Invalid idempotency key');
  const prior=await scope.db.query<{actor_id:string;matches:boolean;result:unknown}>("SELECT actor_id,(proposal-'expected_version')=($3::jsonb-'expected_version') AS matches,result FROM purchase_operations WHERE run_id=$1 AND idempotency_key=$2",[scope.context.run_id,input.idempotency_key,proposal]);
  if(prior.rows[0]){if(prior.rows[0].actor_id!==scope.context.actor_id||!prior.rows[0].matches)throw new GroundError('CONFLICT','Idempotency key belongs to a different purchase operation');return {...operationResultSchema.parse(prior.rows[0].result),status:'already_applied'};}
  return proposal.type==='register_purchase'?this.record(scope,input,proposal):this.confirm(scope,input,proposal);
 }
 private async scope(context:ActorContext,tx:TransactionContext,lock:'SHARE'|'UPDATE'='UPDATE'):Promise<Scope>{
  const parsed=actorContextSchema.parse(context),db=this.deps.transactions.client(tx);
  if(!(await db.query(`SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR ${lock}`,[parsed.run_id,parsed.project_id])).rowCount)throw new GroundError('CONFLICT','Scenario is no longer active');
  const project=await db.query<{version:number}>(`SELECT version FROM projects WHERE id=$1 FOR ${lock}`,[parsed.project_id]);
  const member=await db.query<{roles:unknown}>('SELECT roles FROM members WHERE id=$1 AND project_id=$2',[parsed.actor_id,parsed.project_id]);if(!member.rows[0])throw new GroundError('FORBIDDEN','Project membership required');const roles=actorContextSchema.shape.roles.parse(member.rows[0].roles);if(!roles.length)throw new GroundError('FORBIDDEN','Project role required');
  return {db,tx,context:{...parsed,roles},version:project.rows[0]?.version??0};
 }
 private async evidence(scope:Scope,ids:string[]){for(const id of ids){const valid=await scope.db.query('SELECT id FROM private_files WHERE id=$1 AND project_id=$2 AND run_id=$3 UNION ALL SELECT id FROM ingestion_inputs WHERE id=$1 AND project_id=$2 AND run_id=$3',[id,scope.context.project_id,scope.context.run_id]);if(!valid.rowCount)throw new GroundError('FORBIDDEN','Evidence is outside this project');}}
 private conflict(scope:Scope,proposal:OperationProposal){if(proposal.expected_version!==scope.version)throw new GroundError('CONFLICT','Project changed; refresh before recording this action');}
 private async previousEntity(scope:Scope,id:string,type:'register_purchase'|'confirm_receipt'):Promise<OperationResult>{const row=(await scope.db.query<{result:unknown}>("SELECT result FROM purchase_operations WHERE run_id=$1 AND proposal->>'type'=$3 AND EXISTS(SELECT 1 FROM jsonb_array_elements(result->'state_diff') d WHERE d->>'entity_id'=$2) LIMIT 1",[scope.context.run_id,id,type])).rows[0];if(!row)throw new GroundError('CONFLICT','Existing purchase requires review');return {...operationResultSchema.parse(row.result),status:'already_applied'};}
 private async record(scope:Scope,input:ExecutionEnvelope,proposal:Extract<OperationProposal,{type:'register_purchase'}>):Promise<OperationResult>{
  const fields=proposal.fields;
  const document=await scope.db.query('SELECT id FROM private_files WHERE project_id=$1 AND run_id=$2 AND sha256=$3 AND id=ANY($4::uuid[]) AND (content_type=\'application/pdf\' OR content_type LIKE \'image/%\')',[scope.context.project_id,scope.context.run_id,fields.document_hash,proposal.evidence_ids]);if(!document.rowCount)throw new GroundError('VALIDATION_ERROR','Attach the original invoice with its matching hash');
  const lines=fields.lines.map(line=>{if(line.unit_price===null||decimal(line.unit_price).lt(0))throw new GroundError('VALIDATION_ERROR','Confirma el precio unitario de cada línea de la factura.');return {...line,quantity:decimal(line.quantity).toFixed(),unit_price:decimal(line.unit_price).toFixed(),total:moneyTotal(line.quantity,line.unit_price)};});
  for(const line of lines)if(!(await scope.db.query('SELECT id FROM materials WHERE id=$1 AND project_id=$2',[line.material_id,scope.context.project_id])).rowCount)throw new GroundError('VALIDATION_ERROR','Confirma el material de la factura.');
  const total=lines.reduce((value,line)=>add(value,line.total),'0');const issuerKey=key(fields.issuer),referenceKey=key(fields.reference);
  const fingerprint=createHash('sha256').update(JSON.stringify({issuer:issuerKey,reference:referenceKey,date:fields.invoice_date??null,currency:fields.currency,lines:[...lines].sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))})).digest('hex');
  const duplicate=(await scope.db.query<{id:string;content_hash:string}>('SELECT id,content_hash FROM purchases WHERE run_id=$1 AND (document_hash=$2 OR (issuer_key=$3 AND reference_key=$4))',[scope.context.run_id,fields.document_hash,issuerKey,referenceKey])).rows[0];
  if(duplicate){if(duplicate.content_hash!==fingerprint)throw new GroundError('CONFLICT','La factura coincide con una registrada, pero sus datos son diferentes. Requiere revisión.');return this.previousEntity(scope,duplicate.id,'register_purchase');}
  this.conflict(scope,proposal);const id=randomUUID();
  await scope.db.query("INSERT INTO purchases(id,project_id,run_id,actor_id,source_message_id,issuer,reference,invoice_date,issuer_key,reference_key,document_hash,currency,total,status,version,evidence_ids,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'recorded',1,$14,$15)",[id,scope.context.project_id,scope.context.run_id,scope.context.actor_id,input.source_message_id,fields.issuer,fields.reference,fields.invoice_date??null,issuerKey,referenceKey,fields.document_hash,fields.currency,total,proposal.evidence_ids,fingerprint]);
  for(const line of lines)await scope.db.query('INSERT INTO purchase_lines(id,purchase_id,material_id,quantity,received_quantity,unit,unit_price,total) VALUES($1,$2,$3,$4,0,$5,$6,$7)',[randomUUID(),id,line.material_id,line.quantity,line.unit,line.unit_price,line.total]);
  return this.commit(scope,input,proposal,'purchase.recorded',id,[{entity_type:'purchase',entity_id:id,before:{},after:{status:'recorded'}}],proposal.evidence_ids);
 }
 private async confirm(scope:Scope,input:ExecutionEnvelope,proposal:Extract<OperationProposal,{type:'confirm_receipt'}>):Promise<OperationResult>{
  const purchase=await this.read(scope,proposal.entity_ids.purchase_id);const lines=proposal.fields.lines.map(line=>({...line,quantity:decimal(line.quantity).toFixed()})).sort((a,b)=>a.line_id.localeCompare(b.line_id));
  if(!lines.length||new Set(lines.map(line=>line.line_id)).size!==lines.length)throw new GroundError('VALIDATION_ERROR','Confirm each receipt line once');
  const existing=(await scope.db.query<{id:string;matches:boolean}>('SELECT id,lines=$4::jsonb AS matches FROM purchase_receipts WHERE purchase_id=$1 AND run_id=$2 AND source_message_id=$3',[purchase.id,scope.context.run_id,input.source_message_id,JSON.stringify(lines)])).rows[0];
  if(existing){if(!existing.matches)throw new GroundError('CONFLICT','This receipt source has different quantities');return this.previousEntity(scope,existing.id,'confirm_receipt');}
  if(purchase.status==='received'){
   const last=(await scope.db.query<{id:string;matches:boolean}>('SELECT id,lines=$2::jsonb AS matches FROM purchase_receipts WHERE purchase_id=$1 ORDER BY confirmed_at DESC LIMIT 1',[purchase.id,JSON.stringify(lines)])).rows[0];if(last?.matches)return this.previousEntity(scope,last.id,'confirm_receipt');throw new GroundError('CONFLICT','The purchase is already fully received. Review the existing receipt.');
  }
  this.conflict(scope,proposal);
  for(const item of lines){const line=purchase.lines.find(line=>line.id===item.line_id);if(!line)throw new GroundError('VALIDATION_ERROR','Receipt line is not part of this purchase');if(decimal(item.quantity).gt(decimal(line.quantity).minus(line.received_quantity)))throw new GroundError('VALIDATION_ERROR','Received quantity exceeds the remaining invoice quantity. Review the discrepancy.');}
  const id=randomUUID(),diff:OperationResult['state_diff']=[],movementEvents:string[]=[];
  await scope.db.query('INSERT INTO purchase_receipts(id,purchase_id,project_id,run_id,actor_id,source_message_id,lines,confirmed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,purchase.id,scope.context.project_id,scope.context.run_id,scope.context.actor_id,input.source_message_id,JSON.stringify(lines),scope.context.trusted_time]);
  let version=scope.version;
  for(const item of lines){const line=purchase.lines.find(line=>line.id===item.line_id);if(!line)throw new GroundError('VALIDATION_ERROR','Receipt line missing');const movement=await this.deps.inventory.receive({context:scope.context,material_id:line.material_id,quantity:item.quantity,unit:line.unit,receipt_line_id:id,idempotency_key:`receipt:${id}:${line.id}`,evidence_ids:proposal.evidence_ids,expected_version:version},scope.tx);if(!['applied','already_applied'].includes(movement.status))throw new GroundError('CONFLICT','Inventory changed before receipt confirmation');version=movement.project_version;diff.push(...movement.state_diff);movementEvents.push(...movement.event_ids);await scope.db.query('UPDATE purchase_lines SET received_quantity=received_quantity+$2 WHERE id=$1',[line.id,item.quantity]);}
  const remaining=(await scope.db.query<{pending:boolean}>('SELECT bool_or(received_quantity<quantity) AS pending FROM purchase_lines WHERE purchase_id=$1',[purchase.id])).rows[0]?.pending;const status=remaining?'partially_received':'received';await scope.db.query('UPDATE purchases SET status=$2,version=version+1 WHERE id=$1',[purchase.id,status]);
  return this.commit({...scope,version},input,proposal,'receipt.confirmed',id,[...diff,{entity_type:'receipt',entity_id:id,before:{},after:{purchase_id:purchase.id,status}},{entity_type:'purchase',entity_id:purchase.id,before:{status:purchase.status},after:{status}}],proposal.evidence_ids,movementEvents);
 }
 private async commit(scope:Scope,input:ExecutionEnvelope,proposal:OperationProposal,type:'purchase.recorded'|'receipt.confirmed',entity:string,diff:OperationResult['state_diff'],evidence:string[],relatedEvents:string[]=[]):Promise<OperationResult>{
  const version=scope.version+1,id=randomUUID(),eventId=randomUUID();const project=await scope.db.query<{event_sequence:string}>('UPDATE projects SET version=$2,event_sequence=event_sequence+1 WHERE id=$1 RETURNING event_sequence',[scope.context.project_id,version]);
  await scope.db.query('INSERT INTO domain_events(event_id,project_id,run_id,sequence,project_version,operation_id,type,occurred_at,evidence_ids,payload,schema_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1)',[eventId,scope.context.project_id,scope.context.run_id,project.rows[0]?.event_sequence,version,id,type,scope.context.trusted_time,evidence,{entity_id:entity,entity_version:version,summary:type==='purchase.recorded'?'Invoice recorded; receipt pending':'Physical receipt recorded',changed_fields:['status']}]);
  const result=operationResultSchema.parse({operation_id:id,status:'applied',event_ids:[...relatedEvents,eventId],state_diff:diff,pending_actions:[],project_version:version,evidence_ids:evidence});await scope.db.query('INSERT INTO purchase_operations(id,project_id,run_id,actor_id,idempotency_key,proposal,result) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,scope.context.project_id,scope.context.run_id,scope.context.actor_id,input.idempotency_key,proposal,result]);return result;
 }
 private async read(scope:Scope,id:string):Promise<Purchase>{
  const row=(await scope.db.query<Record<string,unknown>>('SELECT id,project_id,run_id,issuer,reference,to_char(invoice_date,\'YYYY-MM-DD\') AS invoice_date,currency,total::text,status,version,evidence_ids FROM purchases WHERE id=$1 AND project_id=$2 AND run_id=$3',[id,scope.context.project_id,scope.context.run_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Purchase not found');
  const lines=await scope.db.query<Record<string,unknown>>('SELECT l.id,l.material_id,m.name AS material_name,l.quantity::text,l.received_quantity::text,l.unit,l.unit_price::text,l.total::text FROM purchase_lines l JOIN materials m ON m.id=l.material_id WHERE purchase_id=$1 ORDER BY l.id',[id]);const receipts=await scope.db.query<{id:string;confirmed_at:Date;lines:unknown}>('SELECT id,confirmed_at,lines FROM purchase_receipts WHERE purchase_id=$1 ORDER BY confirmed_at',[id]);
  return purchaseSchema.parse({...row,lines:lines.rows,receipts:receipts.rows.map(receipt=>({...receipt,confirmed_at:receipt.confirmed_at.toISOString()}))});
 }
 async list(context:ActorContext,tx?:TransactionContext):Promise<PurchaseList>{if(!tx)return this.deps.transactions.run(current=>this.list(context,current));const scope=await this.scope(context,tx,'SHARE');const ids=await scope.db.query<{id:string}>('SELECT id FROM purchases WHERE project_id=$1 AND run_id=$2 ORDER BY reference,id LIMIT 100',[scope.context.project_id,scope.context.run_id]);const purchases:Purchase[]=[];for(const {id}of ids.rows){const purchase=await this.read(scope,id);purchases.push(costs(scope.context)?purchase:{...purchase,total:null,evidence_ids:[],lines:purchase.lines.map(line=>({...line,unit_price:null,total:null}))});}return purchaseListSchema.parse({purchases,project_version:scope.version,can_receive:receive(scope.context),can_view_costs:costs(scope.context)});}
}
