import { useEffect,useRef,useState,type FormEvent } from 'react';
import { operationResultSchema,purchaseListSchema,type Purchase,type PurchaseList } from '@ground/contracts';
import { apiRequest } from '../../lib/api-client';
import { formatDate,formatMoney,formatQuantity,formatTimestamp } from '../../lib/formatters';
import { Button,Card,EmptyState,ErrorState,EvidenceLink,Field,LoadingState,StatusBadge } from '../../ui';
import './purchases.css';
export function PurchasesPanel({projectId,csrfToken}:{projectId:string;csrfToken:string}){
 const [data,setData]=useState<PurchaseList|null>(null),[error,setError]=useState<string|null>(null);
 async function reload(){try{setData(await apiRequest(`/api/projects/${projectId}/purchases`,{schema:purchaseListSchema}));setError(null);}catch(error){setError(error instanceof Error?error.message:'Could not load invoices.');}}
 useEffect(()=>{let active=true;const controller=new AbortController();apiRequest(`/api/projects/${projectId}/purchases`,{schema:purchaseListSchema,signal:controller.signal}).then(value=>{if(active)setData(value);},error=>{if(active)setError(error instanceof Error?error.message:'Could not load invoices.');});return()=>{active=false;controller.abort();};},[projectId]);
 return <section className="purchases-panel" aria-label="Invoices and physical receipts"><div className="purchases-heading"><h2>Invoices & receipts</h2><Button variant="secondary" onClick={()=>void reload()}>Refresh invoices</Button></div>{error&&<ErrorState message={error} onRetry={()=>void reload()}/>} {!data&&!error&&<LoadingState label="Loading invoices…"/>}{data&&<PurchaseListView data={data} projectId={projectId} csrfToken={csrfToken} onChanged={reload}/>}</section>;
}
export function PurchaseListView({data,projectId,csrfToken,onChanged}:{data:PurchaseList;projectId:string;csrfToken:string;onChanged:()=>Promise<void>}){
 if(!data.purchases.length)return <EmptyState title="No invoices recorded">Send an invoice through the authorized Telegram conversation. Stock changes only after a physical receipt is confirmed.</EmptyState>;
 return <div className="purchases-list">{data.purchases.map(purchase=><PurchaseCard key={purchase.id} purchase={purchase} data={data} projectId={projectId} csrfToken={csrfToken} onChanged={onChanged}/>)}</div>;
}
function PurchaseCard({purchase,data,projectId,csrfToken,onChanged}:{purchase:Purchase;data:PurchaseList;projectId:string;csrfToken:string;onChanged:()=>Promise<void>}){
 const [showReceipt,setShowReceipt]=useState(false);
 return <Card title={purchase.reference??'Invoice reference unknown'}><div className="purchase-overview"><div><p>{purchase.issuer??'Issuer unknown'}</p><p className="g-metadata">{purchase.invoice_date?formatDate(purchase.invoice_date):'Invoice date unknown'}</p></div>{data.can_view_costs&&<strong className="purchase-total g-number">{formatMoney(purchase.total)}</strong>}</div><p><StatusBadge status={purchase.status==='received'?'completed':'pending'}/> <span>{purchase.status==='received'?'Physical receipt complete':purchase.status==='partially_received'?'Partially received':'Invoice recorded · receipt pending'}</span></p><div className="purchase-lines" role="list">{purchase.lines.map(line=><div className="purchase-line" role="listitem" key={line.id}><strong>{line.material_name}</strong><span>Invoiced {formatQuantity(line.quantity,line.unit)} · Received {formatQuantity(line.received_quantity,line.unit)}</span>{data.can_view_costs&&<span>{formatMoney(line.unit_price)} per {line.unit} · {formatMoney(line.total)}</span>}</div>)}</div>{purchase.evidence_ids.length>0&&<div className="purchase-evidence">{purchase.evidence_ids.map(id=><EvidenceLink key={id} projectId={projectId} evidenceId={id} type="Private source">View invoice evidence</EvidenceLink>)}</div>}{purchase.receipts.map(receipt=><p className="g-metadata" key={receipt.id}>Receipt confirmed {formatTimestamp(receipt.confirmed_at)} · {receipt.lines.length} line{receipt.lines.length===1?'':'s'}</p>)}{data.can_receive&&purchase.status!=='received'&&<><Button variant="secondary" onClick={()=>setShowReceipt(value=>!value)}>{showReceipt?'Close receipt form':'Confirm receipt'}</Button>{showReceipt&&<ReceiptForm purchase={purchase} projectId={projectId} projectVersion={data.project_version} csrfToken={csrfToken} onChanged={async()=>{await onChanged();setShowReceipt(false);}}/>}</>}{!data.can_receive&&purchase.status!=='received'&&<p className="g-metadata">A supervisor confirms the physical delivery.</p>}</Card>;
}
function ReceiptForm({purchase,projectId,projectVersion,csrfToken,onChanged}:{purchase:Purchase;projectId:string;projectVersion:number;csrfToken:string;onChanged:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const operationKey=useRef(crypto.randomUUID());
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const lines=purchase.lines.map(line=>({line_id:line.id,quantity:String(form.get(line.id)??'').trim()})).filter(line=>line.quantity!=='');if(!lines.length){setError('Enter at least one quantity you physically received.');return;}setBusy(true);setError(null);try{await apiRequest(`/api/projects/${projectId}/purchases/${purchase.id}/receipts`,{method:'POST',schema:operationResultSchema,csrfToken,idempotencyKey:operationKey.current,body:{type:'confirm_receipt',entity_ids:{purchase_id:purchase.id},fields:{lines},expected_version:projectVersion,evidence_ids:purchase.evidence_ids}});await onChanged();}catch(error){setError(error instanceof Error?error.message:'Could not confirm the receipt. Refresh invoices before retrying.');}finally{setBusy(false);}}
 return <form className="purchase-receipt-form" onSubmit={event=>void submit(event)}><h3>Physical delivery</h3><p>Enter only the quantities checked on site. Leave undelivered lines blank. A quantity above the outstanding invoice needs review.</p>{purchase.lines.map(line=><Field key={line.id} name={line.id} label={`${line.material_name} received now (${line.unit})`} inputMode="decimal" pattern="[0-9]+([.][0-9]+)?" placeholder="Quantity received"/>)}<label className="purchase-confirmation"><input type="checkbox" required/> I checked this physical delivery and confirm these quantities.</label>{error&&<ErrorState message={error}/>}<Button type="submit" loading={busy}>Record physical receipt</Button></form>;
}
