import { createHash,createHmac,timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { GroundError,candidateCalculationSchema,type CandidateCalculation,type RequestProposal,type SourcingSelection } from '@ground/contracts';
import { decimal,multiply,add } from '@ground/domain';
export const configSchema=z.object({test_address:z.string().nullable(),test_recipient_id:z.string().nullable(),test_recipient_reachable:z.boolean(),desired_delivery_date:z.string(),material:z.unknown()});
export type ProcurementConfig=z.infer<typeof configSchema>;
function canonical(value:unknown):string {if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`;return JSON.stringify(value)??'null';}
export function hash(value:unknown){return createHash('sha256').update(canonical(value)).digest('hex');}
export function payloadHash(proposal:RequestProposal){const {content_hash:_hash,status:_status,...signed}=proposal;return hash(signed);}
export function checkpointToken(secret:string,proposal:RequestProposal){if(secret.length<32)throw new GroundError('NOT_READY','SESSION_SECRET must contain at least 32 characters');return createHmac('sha256',secret).update(`${proposal.id}:${proposal.version}:${proposal.checkpoint_id}:${proposal.content_hash}`).digest('hex');}
export function verifyToken(secret:string,proposal:RequestProposal,token:string,stored:string){const supplied=Buffer.from(hash(token),'hex'),expected=Buffer.from(stored,'hex');if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected)||hash(checkpointToken(secret,proposal))!==stored)throw new GroundError('FORBIDDEN','Checkpoint token rejected');}
export function calculation(selection:SourcingSelection,quantity?:number):CandidateCalculation {const initial=selection.calculation;if(initial){const boxes=quantity??initial.required_boxes;const subtotal=initial.converted_price===null?null:multiply(String(boxes),initial.converted_price);return candidateCalculationSchema.parse({...initial,required_boxes:boxes,material_subtotal:subtotal,known_total:subtotal!==null&&initial.known_transport!==null&&initial.known_tax!==null?add(add(subtotal,initial.known_transport),initial.known_tax):null,inputs:{...initial.inputs,...(quantity!==undefined?{reviewed_quantity:String(quantity)}:{})},unresolved_fields:[...initial.unresolved_fields,...(quantity!==undefined&&quantity!==initial.required_boxes?['reviewed quantity differs from calculated need']:[])]});}const boxes=quantity??decimal(selection.need.net_quantity).toNumber();if(!Number.isSafeInteger(boxes)||boxes<=0)throw new GroundError('VALIDATION_ERROR','A positive whole-box quantity is required');return candidateCalculationSchema.parse({candidate_id:selection.id,candidate_version:0,need_id:selection.need.id,need_version:selection.need.version,required_boxes:boxes,unit_price_basis:null,converted_price:null,material_subtotal:null,known_transport:null,known_tax:null,known_total:null,unresolved_fields:['price','coverage confirmation','transport','tax','availability','lot/shade'],formula:'Persisted required-specification quantity from canonical material need',inputs:{net_quantity:selection.need.net_quantity,reviewed_quantity:String(boxes)}});}
export function requestText(input:{id:string;specification:string;boxes:number;address:string;date:string;selection:SourcingSelection}){const candidate=input.selection.candidate;const text=`Solicitud de cotización · La Arboleda · DEMO\nMaterial: ${input.specification}\nCantidad: ${input.boxes} cajas\nDestino: ${input.address}\nFecha solicitada: ${input.date}\nReferencia pública: ${candidate?.source_url??'pendiente'}\nPrecio publicado: ${candidate?.published_price!==null&&candidate?.published_price!==undefined?`${candidate.published_price} ${candidate.currency??'moneda por confirmar'} / ${candidate.sale_unit??'unidad por confirmar'}`:'por confirmar'}\nConfirmar disponibilidad, lote/tono, transporte, total y fecha de entrega.\nSolicitud: ${input.id}`;if(text.length>3500)throw new GroundError('VALIDATION_ERROR','Request text exceeds the channel limit');return text;}
