import { it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { ProcurementService } from './service';
import { isolatedDatabase } from '../../infra/test-database';
import { PgTransactions } from '../../infra/database';
import { PgJobQueue } from '../../infra/jobs';
import { configureDemo,seedDemo,demoProjectId } from '../project/seed';
import { manifestSchema } from '../project/manifest';
import { PgProjectRepository } from '../project/repository';
import { SiteService } from '../site';
import { SourcingService } from '../sourcing';
import { ExaClient } from '../../adapters/exa';
import { LiveService } from '../live';
import type { ActorContext } from '@ground/contracts';
it.skipIf(!process.env['TEST_DATABASE_URL'])('binds supervisor approval to current exact version and one dispatch outbox',async()=>{
 const fixture=await isolatedDatabase(process.env['TEST_DATABASE_URL']!);const transactions=new PgTransactions(fixture.pool),queue=new PgJobQueue(transactions),projects=new PgProjectRepository(transactions);let now=new Date('2026-09-12T12:00:00Z');
 try{const manifest=manifestSchema.parse(JSON.parse(await readFile(new URL('../../../../../demo/manifest.json',import.meta.url),'utf8')));manifest.test_address='Demo test address';manifest.test_recipient_id='999';manifest.test_recipient_reachable=true;manifest.material.brand='Fixture';manifest.material.reference='DEMO';manifest.material.finish='Grey';await configureDemo(transactions,manifest,Object.fromEntries(manifest.members.map(m=>[m.username,randomUUID()])));const run=await seedDemo(transactions,manifest);const member=await fixture.pool.query<{id:string;username:string;roles:ActorContext['roles']}>('SELECT id,username,roles FROM members WHERE project_id=$1',[demoProjectId]);const actor=(name:string):ActorContext=>{const m=member.rows.find(row=>row.username===name);if(!m)throw Error('Missing member');return {actor_id:m.id,project_id:demoProjectId,run_id:run,roles:m.roles,permissions:['costs','approve'],trusted_time:now.toISOString()};};const ana=actor('ana'),worker=actor('luis');const site=new SiteService({transactions,queue});await site.execute({context:ana,proposal:{type:'consume_material',entity_ids:{material_id:'00000000-0000-4000-8000-000000000020',location_id:'00000000-0000-4000-8000-000000000010'},fields:{quantity:'8',unit:'box'},evidence_ids:[],expected_version:0},source_message_id:randomUUID(),idempotency_key:'consume'});const need=(await projects.snapshot(ana)).needs[0]!;
 const sourcing=new SourcingService({transactions,projects,queue,adapter:new ExaClient('fixture',async()=>new Response(JSON.stringify({results:[{url:'https://example.com/fixture',title:'Fixture tile',text:'Reference: DEMO\nFinish: Grey\nCoverage: 1.26 m2/box\nPrice: COP 55000 / box\nDelivery: 2026-09-13\nTransport: 30000 COP\nTax: 0 COP'}]}),{status:200}))});await sourcing.research(ana,need);const candidate=(await sourcing.comparison(ana,need.id)).rows[0]!.candidate.id;const live=new LiveService(transactions,projects);const service=new ProcurementService({transactions,projects,queue,sourcing,checkpoints:live,secret:'fixture-secret-with-at-least-32-characters',clock:{now:()=>now}});const input={need_id:need.id,need_version:need.version,candidate_id:candidate};
 const first=await service.create(ana,input);const decision={proposal_id:first.proposal.id,proposal_version:first.proposal.version,decision:'approve' as const,checkpoint_token:first.checkpoint_token!};await expect(service.decide(worker,decision)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(service.decide({...ana,project_id:randomUUID()},decision)).rejects.toBeDefined();now=new Date('2026-09-12T12:31:00Z');await expect(service.decide(ana,decision)).rejects.toMatchObject({code:'EXPIRED'});
 const current=await service.create(ana,input);const approve={...decision,proposal_id:current.proposal.id,checkpoint_token:current.checkpoint_token!};const approved=await service.decide(ana,approve);expect((await service.decide(ana,approve)).id).toBe(approved.id);expect((await transactions.run(tx=>service.authorizedDispatch(ana,current.proposal.id,1,tx))).status).toBe('pending');expect((await fixture.pool.query("SELECT 1 FROM scheduled_jobs WHERE kind='dispatch_request' AND run_id=$1",[run])).rowCount).toBe(1);
 const stalePrice=await service.create(ana,input);await fixture.pool.query("UPDATE supplier_candidates SET candidate=jsonb_set(candidate,'{published_price}','\"56000\"'),version=version+1 WHERE id=$1",[candidate]);await expect(service.decide(ana,{...approve,proposal_id:stalePrice.proposal.id,checkpoint_token:stalePrice.checkpoint_token!})).rejects.toMatchObject({code:'CONFLICT'});
 const spec=await service.create(ana,{...input,candidate_id:null});await fixture.pool.query("UPDATE projects SET configuration=jsonb_set(configuration,'{test_recipient_id}','\"changed\"') WHERE id=$1",[demoProjectId]);await expect(service.decide(ana,{...approve,proposal_id:spec.proposal.id,checkpoint_token:spec.checkpoint_token!})).rejects.toMatchObject({code:'CONFLICT'});await fixture.pool.query('UPDATE projects SET configuration=$2 WHERE id=$1',[demoProjectId,manifest]);
 await transactions.run(async tx=>{await transactions.client(tx).query('UPDATE procurement_needs SET version=version+1,net_quantity=19 WHERE id=$1',[need.id]);await service.changed({context:ana,operation_id:randomUUID(),need_id:need.id,need_version:2,reason:'Corrected quantity'},tx);});expect((await fixture.pool.query<{status:string}>('SELECT status FROM outbound_requests WHERE proposal_id=$1',[current.proposal.id])).rows[0]?.status).toBe('cancelled');await expect(service.decide(ana,{...approve,proposal_id:spec.proposal.id,checkpoint_token:spec.checkpoint_token!})).rejects.toMatchObject({code:'CONFLICT'});

 const editable=await service.create(ana,{...input,need_version:2,candidate_id:null});const changed=await service.change(ana,editable.proposal.id,{...input,need_version:2,candidate_id:null,quantity:21,expected_version:1});expect(changed.proposal.version).toBe(2);expect(changed.proposal.calculation.required_boxes).toBe(21);await expect(service.decide(ana,{...approve,proposal_id:editable.proposal.id,checkpoint_token:editable.checkpoint_token!})).rejects.toMatchObject({code:'CONFLICT'});const restored=new ProcurementService({transactions,projects,queue,sourcing,checkpoints:new LiveService(transactions,projects),secret:'fixture-secret-with-at-least-32-characters',clock:{now:()=>now}});expect((await restored.get(ana,changed.proposal.id)).checkpoint_token).toBe(changed.checkpoint_token);await restored.decide(ana,{proposal_id:changed.proposal.id,proposal_version:2,decision:'reject',checkpoint_token:changed.checkpoint_token!});expect((await restored.get(ana,changed.proposal.id)).proposal.status).toBe('rejected');
 const started=await service.create(ana,{...input,need_version:2,candidate_id:null});await service.decide(ana,{proposal_id:started.proposal.id,proposal_version:1,decision:'approve',checkpoint_token:started.checkpoint_token!});await fixture.pool.query("UPDATE outbound_requests SET status='sending' WHERE proposal_id=$1",[started.proposal.id]);await transactions.run(async tx=>{await transactions.client(tx).query('UPDATE procurement_needs SET version=3,net_quantity=18 WHERE id=$1',[need.id]);await service.changed({context:ana,operation_id:randomUUID(),need_id:need.id,need_version:3,reason:'Changed after claim'},tx);});expect((await service.get(ana,started.proposal.id)).amendment_required).toBe(true);expect((await fixture.pool.query<{status:string}>('SELECT status FROM outbound_requests WHERE proposal_id=$1',[started.proposal.id])).rows[0]?.status).toBe('sending');
 }finally{await fixture.close();}
});
