import { GroundError,actorContextSchema,requestProposalSchema,sourcingSelectionSchema,type ActorContext,type RequestProposal,type SourcingSelection,type TransactionContext } from '@ground/contracts';
import { PgTransactions,type Clock } from '../../infra/database';
import { configSchema,type ProcurementConfig } from './payload';
export interface Scope {context:ActorContext;configuration:ProcurementConfig;tx:TransactionContext;}
export interface StoredProposal {proposal:RequestProposal;selection:SourcingSelection;token_hash:string;configuration_hash:string;alternative_reviewed:boolean;}
export class ProposalRepository {
 constructor(readonly transactions:PgTransactions,private readonly clock:Clock){}
 async scope(input:ActorContext,tx:TransactionContext,write=true):Promise<Scope>{const context=actorContextSchema.parse({...input,trusted_time:this.clock.now().toISOString()});const db=this.transactions.client(tx);const active=await db.query(`SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR ${write?'UPDATE':'SHARE'}`,[context.run_id,context.project_id]);if(!active.rowCount)throw new GroundError('CONFLICT','Scenario is no longer active');const project=await db.query<{configuration:unknown}>(`SELECT configuration FROM projects WHERE id=$1 FOR ${write?'UPDATE':'SHARE'}`,[context.project_id]);const member=await db.query<{roles:unknown}>('SELECT roles FROM members WHERE id=$1 AND project_id=$2',[context.actor_id,context.project_id]);const row=member.rows[0],config=project.rows[0];if(!row||!config)throw new GroundError('FORBIDDEN','Project membership required');const roles=actorContextSchema.shape.roles.parse(row.roles);return {context:{...context,roles},configuration:configSchema.parse(config.configuration),tx};}
 authorize(scope:Scope,approve=false){if(!scope.context.roles.some(role=>(approve?['admin','supervisor']:['admin','supervisor','purchasing']).includes(role)))throw new GroundError('FORBIDDEN',approve?'Supervisor approval required':'Procurement access required');}
 async read(scope:Scope,id:string,version?:number):Promise<StoredProposal>{const result=await this.transactions.client(scope.tx).query<Record<string,unknown>>("SELECT p.*,to_char(p.desired_date,'YYYY-MM-DD') AS desired_date,s.snapshot AS selection FROM request_proposals p JOIN sourcing_selections s ON s.id=p.selection_id WHERE p.id=$1 AND p.project_id=$2 AND p.run_id=$3 AND ($4::integer IS NULL OR p.version=$4) ORDER BY p.version DESC LIMIT 1",[id,scope.context.project_id,scope.context.run_id,version??null]);const row=result.rows[0];if(!row)throw new GroundError('NOT_FOUND','Request proposal not found');const fields=Object.fromEntries(Object.keys(requestProposalSchema.shape).map(key=>[key,row[key]]));if(fields['expires_at'] instanceof Date)fields['expires_at']=fields['expires_at'].toISOString();return {proposal:requestProposalSchema.parse(fields),selection:sourcingSelectionSchema.parse(row['selection']),token_hash:String(row['token_hash']),configuration_hash:String(row['configuration_hash']),alternative_reviewed:row['alternative_reviewed']===true};}
 async insert(scope:Scope,value:StoredProposal){const {proposal:p,selection}=value;await this.transactions.client(scope.tx).query('INSERT INTO request_proposals(id,version,project_id,run_id,actor_id,selection_id,need_id,need_version,candidate_id,candidate_version,selected_specification,calculation,recipient_id,address,desired_date,exact_text,content_hash,status,expires_at,checkpoint_id,token_hash,configuration_hash,alternative_reviewed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23)',[p.id,p.version,scope.context.project_id,scope.context.run_id,scope.context.actor_id,selection.id,p.need_id,p.need_version,p.candidate_id,p.candidate_version,p.selected_specification,p.calculation,p.recipient_id,p.address,p.desired_date,p.exact_text,p.content_hash,p.status,p.expires_at,p.checkpoint_id,value.token_hash,value.configuration_hash,value.alternative_reviewed]);}
}
