import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {GroundError,externalObjectLinkSchema,type ActorContext,type ExternalObjectLink,type RemoteObject,type TransactionContext} from '@ground/contracts';
import {PgTransactions} from '../../infra/database';
import type {SyncPlan} from './sync-coordinator';
const recordSchema=z.object({id:z.string().uuid(),project_id:z.string().uuid(),run_id:z.string().uuid(),local_id:z.string().uuid(),object_kind:z.enum(['file','task','document']),identity_key:z.string(),marker:z.string(),remote_id:z.string().nullable(),remote_url:z.string().nullable(),remote_revision:z.string().nullable(),synced_version:z.number().int(),desired_version:z.number().int(),desired_hash:z.string(),status:z.string(),last_error:z.string().nullable(),lease_expires_at:z.date().nullable()});
export type OfficeRecord=z.infer<typeof recordSchema>;
export class OfficeRepository {
 constructor(readonly transactions:PgTransactions){}
 async active(project:string,run:string,tx:TransactionContext,lock:'SHARE'|'UPDATE'='UPDATE'){const db=this.transactions.client(tx);if(!(await db.query(`SELECT id FROM scenario_runs WHERE id=$1 AND project_id=$2 AND status='active' FOR ${lock}`,[run,project])).rowCount)throw new GroundError('CONFLICT','Office job belongs to an inactive run');await db.query(`SELECT id FROM projects WHERE id=$1 FOR ${lock}`,[project]);}
 async claim(plan:Pick<SyncPlan,'project_id'|'run_id'|'local_id'|'object_kind'|'identity_key'|'version'|'hash'>):Promise<OfficeRecord>{return this.transactions.run(async tx=>{await this.active(plan.project_id,plan.run_id,tx);const db=this.transactions.client(tx);let row=(await db.query<Record<string,unknown>>('SELECT * FROM office_objects WHERE run_id=$1 AND object_kind=$2 AND identity_key=$3 FOR UPDATE',[plan.run_id,plan.object_kind,plan.identity_key])).rows[0];if(!row){const result=await db.query<Record<string,unknown>>("INSERT INTO office_objects(id,project_id,run_id,local_id,object_kind,identity_key,marker,synced_version,desired_version,desired_hash,status) VALUES($1,$2,$3,$4,$5,$6,$7,0,$8,$9,'pending') RETURNING *",[randomUUID(),plan.project_id,plan.run_id,plan.local_id,plan.object_kind,plan.identity_key,`ground-${plan.run_id}-${plan.object_kind}-${plan.identity_key}`,plan.version,plan.hash]);row=result.rows[0];}const record=recordSchema.parse(row);if(record.status==='sending'&&record.lease_expires_at&&record.lease_expires_at.getTime()>Date.now())throw new GroundError('PROVIDER_UNAVAILABLE','Office object is already being synchronized',true);return record;});}
 async unavailable(plan:Pick<SyncPlan,'project_id'|'run_id'|'local_id'|'object_kind'|'identity_key'|'version'|'hash'>,message:string){const record=await this.claim(plan);await this.failed(record,'failed',message);}
 async sending(record:OfficeRecord,plan:SyncPlan){await this.transactions.run(async tx=>{await this.active(plan.project_id,plan.run_id,tx);const db=this.transactions.client(tx);const result=await db.query("UPDATE office_objects SET status='sending',desired_version=$2,desired_hash=$3,local_id=$4,attempted_at=now(),lease_expires_at=now()+interval '90 seconds',last_error=NULL WHERE id=$1 AND status=$5 AND remote_id IS NOT DISTINCT FROM $6 AND (status<>'sending' OR lease_expires_at<now())",[record.id,plan.version,plan.hash,plan.local_id,record.status,record.remote_id]);if(!result.rowCount)throw new GroundError('PROVIDER_UNAVAILABLE','Office object is leased',true);await this.event(record,'remote.sync_pending',null,tx);});}
 async remember(record:OfficeRecord,remote:RemoteObject){await this.transactions.run(async tx=>{await this.transactions.client(tx).query('UPDATE office_objects SET remote_id=$2,remote_url=$3,remote_revision=$4 WHERE id=$1',[record.id,remote.id,remote.url,remote.revision]);});record.remote_id=remote.id;record.remote_url=remote.url;record.remote_revision=remote.revision;}
 async complete(record:OfficeRecord,plan:SyncPlan,remote:RemoteObject):Promise<ExternalObjectLink>{await this.transactions.run(async tx=>{await this.active(plan.project_id,plan.run_id,tx);await this.transactions.client(tx).query("UPDATE office_objects SET status='synced',local_id=$2,synced_version=$3,desired_version=$3,desired_hash=$4,remote_id=$5,remote_url=$6,remote_revision=$7,last_error=NULL,lease_expires_at=NULL WHERE id=$1",[record.id,plan.local_id,plan.version,plan.hash,remote.id,remote.url,remote.revision]);await this.event(record,'remote.synced',null,tx);});return externalObjectLinkSchema.parse({provider:'ambiguous',local_id:plan.local_id,object_kind:plan.object_kind,project_id:plan.project_id,run_id:plan.run_id,remote_id:remote.id,remote_url:remote.url,synced_version:plan.version,sync_status:'synced',last_error:null});}
 async failed(record:OfficeRecord,status:'failed'|'uncertain'|'needs_review',message:string){await this.transactions.run(async tx=>{await this.transactions.client(tx).query('UPDATE office_objects SET status=$2,last_error=$3,lease_expires_at=NULL WHERE id=$1',[record.id,status,message]);await this.event(record,'remote.failed',message,tx);});}
 private async event(record:OfficeRecord,type:'remote.sync_pending'|'remote.synced'|'remote.failed',message:string|null,tx:TransactionContext){const db=this.transactions.client(tx);const row=(await db.query<{event_sequence:string;version:number}>('UPDATE projects SET event_sequence=event_sequence+1 WHERE id=$1 RETURNING event_sequence,version',[record.project_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Project missing');await db.query('INSERT INTO domain_events(event_id,project_id,run_id,sequence,project_version,operation_id,type,occurred_at,evidence_ids,payload,schema_version) VALUES($1,$2,$3,$4,$5,$6,$7,now(),$8,$9,1)',[randomUUID(),record.project_id,record.run_id,row.event_sequence,row.version,record.id,type,[],{entity_id:record.local_id,entity_version:record.desired_version,summary:message??(type==='remote.synced'?'Office resource verified':'Office synchronization pending'),changed_fields:['remote_sync']}]);}
 link(record:OfficeRecord):ExternalObjectLink{if(!record.remote_id||!record.remote_url)throw new GroundError('NOT_READY','Remote object has not been created');return externalObjectLinkSchema.parse({provider:'ambiguous',local_id:record.local_id,object_kind:record.object_kind,project_id:record.project_id,run_id:record.run_id,remote_id:record.remote_id,remote_url:record.remote_url,synced_version:record.synced_version,sync_status:record.status==='synced'?'synced':['uncertain','needs_review'].includes(record.status)?'needs_review':record.status==='failed'?'failed':'pending',last_error:record.last_error});}
 async links(context:ActorContext,tx?:TransactionContext):Promise<ExternalObjectLink[]>{if(!tx)return this.transactions.run(current=>this.links(context,current));await this.active(context.project_id,context.run_id,tx,'SHARE');const db=this.transactions.client(tx),member=(await db.query<{roles:string[]}>('SELECT roles FROM members WHERE id=$1 AND project_id=$2',[context.actor_id,context.project_id])).rows[0];if(!member)throw new GroundError('FORBIDDEN','Office link access denied');const financial=member.roles.some(role=>['supervisor','purchasing','admin'].includes(role));const rows=await db.query<Record<string,unknown>>("SELECT o.* FROM office_objects o LEFT JOIN private_files f ON f.id=o.local_id WHERE o.project_id=$1 AND o.run_id=$2 AND o.remote_id IS NOT NULL AND ($3 OR (o.object_kind<>'document' AND COALESCE(f.restricted,false)=false))",[context.project_id,context.run_id,financial]);return rows.rows.map(row=>this.link(recordSchema.parse(row)));}
}
