import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {GroundError,reportSnapshotSchema,roleSchema,type ActorContext,type ExternalObjectLink,type Job,type JobQueue,type PrivateFileStore,type TransactionContext} from '@ground/contracts';
import {AmbiguousClient,documentContains} from '../../adapters/ambiguous';
import {OfficeRepository} from './office-repository';
import {SyncCoordinator} from './sync-coordinator';
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const fileSchema=z.object({id:z.string().uuid(),sha256:z.string(),size_bytes:z.number(),content_type:z.string(),restricted:z.boolean()});
const taskSchema=z.object({id:z.string().uuid(),version:z.number(),status:z.string(),due_at:z.date(),remote_user_id:z.string().nullable(),description:z.string(),location:z.string(),source_message_id:z.string(),evidence_ids:z.array(z.string())});
export class OfficeSyncService {
 private readonly coordinator:SyncCoordinator;
 constructor(private readonly deps:{repository:OfficeRepository;adapter:AmbiguousClient;files:PrivateFileStore;queue:JobQueue;public_base_url:string}){this.coordinator=new SyncCoordinator(deps.repository);}
 links(context:ActorContext,tx?:TransactionContext):Promise<ExternalObjectLink[]>{return this.deps.repository.links(context,tx);}
 async handle(job:Job):Promise<void>{if(!['sync_attachment','sync_assignment','sync_report'].includes(job.kind))throw new GroundError('VALIDATION_ERROR','Unknown office job');if(job.kind==='sync_attachment')await this.file(job,job.payload.subject_id);else if(job.kind==='sync_assignment')await this.task(job);else await this.report(job);}
 private async file(job:Job,fileId:string):Promise<ExternalObjectLink>{
  const file=await this.deps.repository.transactions.run(async tx=>{await this.deps.repository.active(job.project_id,job.run_id,tx,'SHARE');const row=(await this.deps.repository.transactions.client(tx).query<Record<string,unknown>>('SELECT * FROM private_files WHERE id=$1 AND project_id=$2 AND run_id=$3',[fileId,job.project_id,job.run_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Evidence file is missing');return fileSchema.parse(row);});
  if(!file.content_type.startsWith('image/')||file.restricted)throw new GroundError('FORBIDDEN','Only unrestricted report photos are synchronized');
  const link=await this.coordinator.sync({project_id:job.project_id,run_id:job.run_id,local_id:file.id,object_kind:'file',identity_key:file.id,version:1,hash:file.sha256,create:async marker=>this.deps.adapter.uploadEvidence({bytes:await this.deps.files.read(file.id),filename:`photo.${file.content_type==='image/png'?'png':'jpg'}`,content_type:file.content_type,sha256:file.sha256,marker}),read:id=>this.deps.adapter.getFile(id),update:async()=>{throw new GroundError('CONFLICT','Original evidence is immutable');},verify:remote=>this.deps.adapter.verifyFile(remote.id,file.size_bytes,file.content_type,file.sha256),find:marker=>this.deps.adapter.findByMarker('file',marker)});
  if(job.kind==='sync_attachment')await this.wakeTasks(job,file.id);
  return link;
 }
 private async wakeTasks(job:Job,fileId:string):Promise<void>{await this.deps.repository.transactions.run(async tx=>{await this.deps.repository.active(job.project_id,job.run_id,tx);const db=this.deps.repository.transactions.client(tx);const tasks=await db.query<{id:string;version:number}>("SELECT DISTINCT a.id,a.version FROM assignments a LEFT JOIN ingestion_inputs i ON i.project_id=a.project_id AND i.run_id=a.run_id AND i.message->'media' @> $3::jsonb WHERE a.project_id=$1 AND a.run_id=$2 AND (a.evidence_ids && ARRAY[$4::uuid,i.id,i.report_id])",[job.project_id,job.run_id,JSON.stringify([{id:fileId}]),fileId]);for(const task of tasks.rows)await this.deps.queue.enqueue({...job,job_id:randomUUID(),kind:'sync_assignment',dedupe_key:`office-late-photo:${job.run_id}:${task.id}:${task.version}:${fileId}`,payload:{subject_id:task.id,expected_version:task.version},status:'pending',attempts:0,lease_owner:null,lease_expires_at:null,condition:null,last_error:null,result_reference:null},tx);});}
 private async task(job:Job):Promise<ExternalObjectLink>{
  const prepared=await this.deps.repository.transactions.run(async tx=>{await this.deps.repository.active(job.project_id,job.run_id,tx,'SHARE');const db=this.deps.repository.transactions.client(tx);const row=(await db.query<Record<string,unknown>>('SELECT a.id,a.version,a.status,a.due_at,a.evidence_ids,m.remote_user_id,i.description,i.source_message_id,l.name AS location FROM assignments a JOIN members m ON m.id=a.assignee_id JOIN issues i ON i.id=a.issue_id JOIN locations l ON l.id=i.location_id WHERE a.id=$1 AND a.project_id=$2 AND a.run_id=$3',[job.payload.subject_id,job.project_id,job.run_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Assignment missing');const task=taskSchema.parse(row);const photos=await db.query<{id:string}>("SELECT DISTINCT f.id FROM private_files f LEFT JOIN ingestion_inputs source ON source.id::text=$3 AND source.project_id=f.project_id AND source.run_id=f.run_id LEFT JOIN ingestion_inputs related ON related.project_id=f.project_id AND related.run_id=f.run_id AND related.report_id=source.report_id WHERE f.project_id=$1 AND f.run_id=$2 AND f.content_type LIKE 'image/%' AND f.restricted=false AND (f.id=ANY($4::uuid[]) OR source.message->'media' @> jsonb_build_array(jsonb_build_object('id',f.id::text)) OR related.message->'media' @> jsonb_build_array(jsonb_build_object('id',f.id::text)))",[job.project_id,job.run_id,task.source_message_id,task.evidence_ids]);return {task,photos:photos.rows};});
  if(!prepared.task.remote_user_id||!prepared.photos.length){const message=!prepared.task.remote_user_id?'Assignment needs an Ambiguous user mapping; supervisor configuration required':'Task is waiting for its report photo';await this.deps.repository.unavailable({project_id:job.project_id,run_id:job.run_id,local_id:prepared.task.id,object_kind:'task',identity_key:prepared.task.id,version:prepared.task.version,hash:hash(prepared.task)},message);throw new GroundError(!prepared.task.remote_user_id?'NOT_READY':'PROVIDER_UNAVAILABLE',message,Boolean(prepared.task.remote_user_id));}
  const photos:ExternalObjectLink[]=[];for(const photo of prepared.photos)photos.push(await this.file(job,photo.id));const first=photos[0];if(!first)throw new GroundError('NOT_READY','Task evidence is not ready');
  const due=prepared.task.due_at.toISOString();const title=`Revisar ${prepared.task.description} · ${prepared.task.location}`.slice(0,255);const description=`Reporte de obra: ${prepared.task.description}\nUbicación: ${prepared.task.location}\n${photos.map(photo=>photo.remote_url).join('\n')}\nGround: ${this.deps.public_base_url}/projects/${job.project_id}/evidence/${prepared.task.source_message_id}`;
  const assignee=prepared.task.remote_user_id;const desired={title,description,due,assignee,status:prepared.task.status,urls:photos.map(photo=>photo.remote_url)};
  return this.coordinator.sync({project_id:job.project_id,run_id:job.run_id,local_id:prepared.task.id,object_kind:'task',identity_key:prepared.task.id,version:prepared.task.version,hash:hash(desired),create:marker=>this.deps.adapter.createTask({title,description,due_at:due,assignee_id:assignee,evidence_url:first.remote_url,marker,status:prepared.task.status}),read:id=>this.deps.adapter.getTask(id),update:(remote,marker)=>this.deps.adapter.updateTask(remote.id,{desired_version:prepared.task.version,title,due_at:due,assignee_id:assignee,status:prepared.task.status,description,evidence_url:first.remote_url,marker}),verify:async remote=>{const actual=await this.deps.adapter.getTask(remote.id);return actual.title===title&&actual.assignee_id===assignee&&actual.due_at===due&&actual.evidence_url===first.remote_url&&actual.status===({pending:'todo',in_progress:'in_progress',completed:'done',cancelled:'cancelled'}[prepared.task.status])&&photos.every(photo=>actual.description.includes(photo.remote_url));},find:marker=>this.deps.adapter.findByMarker('task',marker)});
 }
 private async report(job:Job):Promise<ExternalObjectLink>{
  const report=await this.deps.repository.transactions.run(async tx=>{await this.deps.repository.active(job.project_id,job.run_id,tx,'SHARE');const row=(await this.deps.repository.transactions.client(tx).query<{snapshot:unknown}>("SELECT snapshot FROM report_snapshots WHERE id=$1 AND project_id=$2 AND run_id=$3 AND audience='financial'",[job.payload.subject_id,job.project_id,job.run_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Stored report is unavailable');return reportSnapshotSchema.parse(row.snapshot);});
  const body=[`Ground report · ${report.date}`,`Project version ${report.version}`,`Generated ${report.generated_at}`, ...report.sections.flatMap(section=>['',section.title,section.text]),'',...report.evidence_ids.map(id=>`${this.deps.public_base_url}/projects/${report.project_id}/evidence/${id}`)].join('\n');
  let intended='';
  return this.coordinator.sync({project_id:job.project_id,run_id:job.run_id,local_id:report.id,object_kind:'document',identity_key:report.date,version:report.version,hash:hash(body),create:marker=>{intended=`${marker}\n${body}`;return this.deps.adapter.createDocument({title:`Ground · ${report.date} · run ${report.run_id.slice(0,8)}`,content:intended,marker});},read:id=>this.deps.adapter.getDocument(id),update:(remote,marker)=>{intended=`${marker}\n${body}`;return this.deps.adapter.updateDocument(remote.id,{observed_revision:remote.revision,content:intended});},verify:async remote=>{const doc=await this.deps.adapter.getDocument(remote.id);const expected=intended||`ground-${job.run_id}-document-${report.date}\n${body}`;return documentContains(doc.content,expected);},find:marker=>this.deps.adapter.findByMarker('document',marker)});
 }
}
