import { z } from 'zod';
import { clarificationSchema, normalizedMessageSchema, GroundError, type ActorContext, type Clarification, type TransactionContext } from '@ground/contracts';
import type { PgTransactions } from '../../infra/database';
import type { StoredInput } from '../ingestion';
import { extractionSchema } from '../../adapters/openrouter/extraction';
export const recordSchema=z.object({input_id:z.string().uuid(),project_id:z.string().uuid(),run_id:z.string().uuid(),status:z.enum(['processing','completed','ignored','needs_input','retryable','pending_handler']),transcript:z.string().nullable(),transcript_reference:z.string().uuid().nullable(),result:extractionSchema.nullable(),metadata:z.record(z.unknown()),error:z.string().nullable(),question_count:z.number().int(),answer_text:z.string().nullable()});
export type InterpretationRecord=z.infer<typeof recordSchema>;
export class InterpretationRepository {
 constructor(private readonly transactions:PgTransactions){}
 async get(input:string,tx:TransactionContext):Promise<InterpretationRecord|null>{const result=await this.transactions.client(tx).query<Record<string,unknown>>('SELECT * FROM interpretation_records WHERE input_id=$1 FOR UPDATE',[input]);return result.rows[0]?recordSchema.parse(result.rows[0]):null;}
 async save(record:InterpretationRecord,tx:TransactionContext):Promise<void>{await this.transactions.client(tx).query('INSERT INTO interpretation_records(input_id,project_id,run_id,status,transcript,transcript_reference,result,metadata,error,question_count,answer_text) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(input_id) DO UPDATE SET status=excluded.status,transcript=excluded.transcript,transcript_reference=excluded.transcript_reference,result=excluded.result,metadata=excluded.metadata,error=excluded.error,question_count=excluded.question_count,answer_text=excluded.answer_text',[record.input_id,record.project_id,record.run_id,record.status,record.transcript,record.transcript_reference,record.result?JSON.stringify(record.result):null,JSON.stringify(record.metadata),record.error,record.question_count,record.answer_text]);}
 async saveClarification(input:string,context:ActorContext,clarification:Clarification,count:number,tx:TransactionContext){await this.transactions.client(tx).query("INSERT INTO interpretation_clarifications(id,input_id,project_id,run_id,clarification,status,question_count) VALUES($1,$2,$3,$4,$5,'pending',$6)",[clarification.id,input,context.project_id,context.run_id,JSON.stringify(clarification),count]);}
 async clarification(id:string,context:ActorContext,tx:TransactionContext){const row=(await this.transactions.client(tx).query<Record<string,unknown>>('SELECT * FROM interpretation_clarifications WHERE id=$1 AND project_id=$2 AND run_id=$3 FOR UPDATE',[id,context.project_id,context.run_id])).rows[0];if(!row)throw new GroundError('NOT_FOUND','Clarification not found');return z.object({input_id:z.string().uuid(),clarification:clarificationSchema,status:z.string(),question_count:z.number()}).parse(row);}
 async resolve(id:string,clarification:Clarification,tx:TransactionContext){await this.transactions.client(tx).query("UPDATE interpretation_clarifications SET status='answered',clarification=$2 WHERE id=$1",[id,JSON.stringify(clarification)]);}
 async latestForInput(input:string,context:ActorContext,tx:TransactionContext):Promise<string|null>{const result=await this.transactions.client(tx).query<{id:string}>("SELECT id FROM interpretation_clarifications WHERE input_id=$1 AND project_id=$2 AND run_id=$3 AND status='pending' ORDER BY question_count DESC LIMIT 1",[input,context.project_id,context.run_id]);return result.rows[0]?.id??null;}
 async linkedMedia(input:StoredInput,tx:TransactionContext){const result=await this.transactions.client(tx).query<{message:unknown}>('SELECT message FROM ingestion_inputs WHERE report_id=$1 AND project_id=$2 AND run_id=$3',[input.report_id??input.id,input.message.project_id,input.message.run_id]);const media=[...input.message.media];for(const row of result.rows)for(const file of normalizedMessageSchema.parse(row.message).media)if(file.sha256&&!media.some(existing=>existing.id===file.id))media.push(file);return media;}
 async derivative(context:ActorContext,id:string,sha256:string,size:number,tx:TransactionContext){await this.transactions.client(tx).query("INSERT INTO private_files(id,project_id,run_id,content_type,sha256,size_bytes,restricted) VALUES($1,$2,$3,'audio/wav',$4,$5,false) ON CONFLICT(id) DO NOTHING",[id,context.project_id,context.run_id,sha256,size]);}
}
